### ISSUE TITLE
Glyph of balance is still broken on the lost characters

### ISSUE THREAD

**Issue by Neonomi** [UnderscoreKilburn/repentance-issues#100]

**Comment by UnderscoreKilburn** [comment]
Could you elaborate? I'm getting coins, bombs and keys with them, not soul hearts.

**Comment by Gemboat** [comment]
I'm seeing this too, on the latest version. The drops I was getting went 1 key, 1 bomb, 15 cents, 5 keys, 5 bombs, trinket -- all as expected. But the drops after that were all soul hearts, 100% of the time.
Tested this through `debug 10` and repeated use of `spawn 10.0.0.1`, but it seems to apply to room clear rewards the same way.

**Comment by Neonomi** [comment]
Yes. If you have all other consumables, it spawn blue hearts 90% of time. Should it work like that?

**Comment by UnderscoreKilburn** [comment]
Oh yeah I see it now, yeah you should just get regular drops instead.
