### ISSUE TITLE
Jacob and Esau trickstery

### ISSUE THREAD

**Issue by Lonrite** [UnderscoreKilburn/repentance-issues#1014]
if you give esau items and kill yourself as Jacob to respawn as Dark Judas, you won't really have any items left despite the tracker showing them

intended or no, reporting just in case

https://www.dropbox.com/s/90cak807mq8z7kv/lol.PNG?dl=0

**Comment by ZMBanshee** [comment]
It's a cache issue, you do have the items but your character is not getting updated to apply them. To get something like knife to apply you'd need to pick up another weapon type, to get rainbow baby to show up you'd need to pick up another familiar, etc... 

If you remember how Small Rock used to be a "delayed" speed down, it's exactly like that.

**Comment by Lonrite** [comment]
yeah small rock is a bit of a meme in AB dailies because of that delay lol
