### ISSUE TITLE
Dr.Fetus + Soy Milk

### ISSUE THREAD

**Issue by Lonrite** [UnderscoreKilburn/repentance-issues#1019]
would be a lot better if it had small bombs similar to scatter bombs and less dangerous overall with that synergy, instead of still having big bombs but no damage

**Comment by ZMBanshee** [comment]
It already does, but I can understand if you don't ever take Dr. Fetus to notice that.

**Comment by Lonrite** [comment]
i had dr.fetus and soy milk today and it didn't look like that but maybe something else messed with it lol.

and yeah its based af to not take dr.fetus, 1 of the most humiliating ways to ruin your run

i somehow won the dr.fetus soy one but what a meme it was

**Comment by Lonrite** [comment]
although I know that rocket in the jar + dr fetus + soy milk works really well at least
