### ISSUE TITLE
Rocket in a Jar is bipolar

### ISSUE THREAD

**Issue by Lonrite** [UnderscoreKilburn/repentance-issues#1021]
this item is largely inconsistent which heavily weakens any motivation to use it, I don't really know if this happened because of montezuma's revenge or no but losing a large streak for no reason still feels shitty, wish this was improved somehow because as of right now I can't trust this item much (even if I like it)

https://clips.twitch.tv/DepressedCrunchyClintEagleEye-c9DHwoHlP5lJ6dD9

**Comment by ZMBanshee** [comment]
Montezuma's Revenge is what caused it yes. Probably related to https://github.com/UnderscoreKilburn/repentance-issues/issues/672 but either way it seems to be fixed.

**Comment by Lonrite** [comment]
damn, well at least it's good it's fixed
