### ISSUE TITLE
Empress?

### ISSUE THREAD

**Issue by Lonrite** [UnderscoreKilburn/repentance-issues#1023]
the card sets you to 0.90 speed sometimes (not even always after it ends), dunno if intended or no (happens even if you don't have a single speed down item or pill or anything like that btw)

**Comment by ZMBanshee** [comment]
Evidence or a way to reproduce it would be nice.

**Comment by Lonrite** [comment]
> Evidence or a way to reproduce it would be nice.

here you go: https://clips.twitch.tv/SmoothEasyOstrichSSSsss-jRmhjAw_yXLDg2ND

**Comment by Lonrite** [comment]
it gives you -0.10 speed somewhat often yeah, on start or after it ends, happened to me again just now

although sometimes you get back the +0.10 you were supposed to have
