### ISSUE TITLE
Azazel's Rage 

### ISSUE THREAD

**Issue by Lonrite** [UnderscoreKilburn/repentance-issues#1084]
Banshee already mentioned Purgatory being worthless in boss challenge rooms / boss rush, however iirc he didn't mention the same thing for Az' Rage so here i am

same stuff basically applies to it sadly

(Edit: nevermind lol, I guess i confused stuff)

**Comment by ZMBanshee** [comment]
Duplicate of https://github.com/UnderscoreKilburn/repentance-issues/issues/1018

**Comment by Lonrite** [comment]
hope that gets fixed 1 day, wish ya'll a smooth sailing of the upcoming patch
