### ISSUE TITLE
Glowing Hour Glass is now even more broken

### ISSUE THREAD

**Issue by Neonomi** [UnderscoreKilburn/repentance-issues#1101]
1. Leave the stage, get 3 charges no matter what
2. Use Glowing Hour Glass
3. Realize that you have an infinite source of 2 charges

**Comment by Lonrite** [comment]
lol

**Comment by Turtier** [comment]
Possibly worth nothing, forget me now + glowing hourglass (+ schoolbag) actually works correctly, using hourglass immediately after forget me now will bring u back to the previous iteration of the floor, giving you back the forget me now, but not your hourglass charges.
