### ISSUE TITLE
Spindown Dice

### ISSUE THREAD

**Issue by Lonrite** [UnderscoreKilburn/repentance-issues#1113]
Spindown would be neat to have in dailies as well if it didn't grant stuff like R Key

the current change just gets rid of little things that differentiate good and great daily plays, little stuff like that is very important to see who understands dailies better on the leaderboard

and at the end of the day it adds neat variety and strategy into daily runs

**Comment by epfly6** [comment]
D7 is not listed as the banned item for dailies...
(437 is D7 id)
![image](https://user-images.githubusercontent.com/36567300/200107400-41b26d97-2451-4a92-82c4-fc72084b118b.png)

**Comment by Lonrite** [comment]
yeah i'll rearrange the post
