### ISSUE TITLE
Duplicated items spawned in Death Certificate closet neglects the teleportation effect

### ISSUE THREAD

**Issue by YazawaAkio** [UnderscoreKilburn/repentance-issues#1118]
As said, if you use Diplopia or Crooked Penny in Death Certificate closet, all duplicate items spawned by the effect can be picked up without teleporting Isaac out.

**Comment by ZMBanshee** [comment]
How this works is going to be changed a bit in the next patch to function more like choices you'd see in angel rooms/boss rush, but the simple act of getting more items without being kicked out is intended at this point, so I'll close this.
