### ISSUE TITLE
Invalid D10 entries?

### ISSUE THREAD

**Issue by epfly6** [UnderscoreKilburn/repentance-issues#1127]
From log:
[INFO] - Cannot add D10 reroll entry to Entity 844.1.0
[INFO] - Cannot add D10 reroll entry to Entity 890.3.1

**Comment by ZMBanshee** [comment]
I think this might be fixed. Can you see if that's still showing up for you?

**Comment by epfly6** [comment]
> I think this might be fixed. Can you see if that's still showing up for you?

No
