### ISSUE TITLE
IBS + Epiphora = Cancels Itself

### ISSUE THREAD

**Issue by Xebarsis** [UnderscoreKilburn/repentance-issues#113]
If I hold my attack in one direction, I get a tears up from Epiphora. However, once IBS is triggered, a poop will not be launched but I'll lose my tear bonus and I'll have to start charging Epiphora over again.

**Comment by Neonomi** [comment]
Just tested. After poop is thrown, Epiphora still at max fire rate. I'm surprised it's not resetting. Don't see a problem tho

**Comment by Xebarsis** [comment]
Hmmm.. you're right. Same results as you when I did just those two items. I must've had another item that broke the interaction.  I'll be posting a video of the run on YouTube probably in the next couple days and link it to this post when I do.

**Comment by Xebarsis** [comment]
I just gave myself every single item that I had in the run, and the bug is not being replicated. I'll just post the video with a timestamp in a couple days.

**Comment by Xebarsis** [comment]
User error, please disregard.
