### ISSUE TITLE
Golden Gilded Key doesn't give a key on pickup

### ISSUE THREAD

**Issue by Buurazu** [UnderscoreKilburn/repentance-issues#1142]
I'm guessing this odd ability of the trinket is tied to its specific subtype. It would be great if the Golden version instead granted you a Golden Key.

I'd suspect that Golden Tick being removable is also the same bug, but that's a fun trait of it.

**Comment by Lonrite** [comment]
Golden Tick being removable is probably intentional but the gilded key thing is unfortunate yeah

**Comment by Rchardon** [comment]
You already reported this with #358

**Comment by Buurazu** [comment]
oh it's been so long i forgot i did already
