### ISSUE TITLE
Rooms with unlockable enemies can cause unavoidable softlocks (and limit room design)

### ISSUE THREAD

**Issue by kittenchilly** [UnderscoreKilburn/repentance-issues#117]
If a room has an unlockable enemy and it gets replaced with another enemy, it can cause softlocks that are unavoidable as well as limit room design if you have to design the room around both the replacer enemy and the unlockable enemy.
This can be fixed by making rooms with unlockable enemies just not show up at all if they aren't unlocked yet. Perhaps with a difficulty that sets if the room should spawn only if the player has The Gate is Open achievement, much like the void portal rooms.

**Comment by ZMBanshee** [comment]
It's just Poison Mind -> Brain causing problems, right? Since Poison Minds can now fly and Brains cannot. I believe the rest of the replacement enemies share the same collision properties as their original counterparts.

**Comment by ZMBanshee** [comment]
I'm closing this since the room this was a problem in for the vanilla game was changed a while back. If you want to reopen this as a suggestion for the sake of helping modded rooms, that's fine.
