### ISSUE TITLE
Mr. ME! 

### ISSUE THREAD

**Issue by Lonrite** [UnderscoreKilburn/repentance-issues#1199]
the dude is terrified of alt path apparently, it crashes sometimes if you try to open the downpour door with him

**Comment by ZMBanshee** [comment]
Similar enough to https://github.com/UnderscoreKilburn/repentance-issues/issues/1143 that I'm going to close this, maybe just leave a mention there that it can occur with other alt path doors if you want

**Comment by Lonrite** [comment]
https://clips.twitch.tv/ExpensiveFastPidgeonTTours-LWmQPKLAteyRXSLs

got it just now on 1.7.9a with mines door. thought it was downpour exclusive but apparently not

I've heard from someone that it crashes both downpour and mines doors so yeah :/

**Comment by luni3359** [comment]
@CoolG0101 please don't post in duplicates, that's why he referenced the other issue

**Comment by Lonrite** [comment]
> @CoolG0101 please don't post in duplicates, that's why he referenced the other issue

yeah makes sense, apologies

i did it just in case but ye its pointless to do
