### ISSUE TITLE
Genesis Trap Door on the Chest Randomly Spawned without Ladder and Regenerated the Floor

### ISSUE THREAD

**Issue by bathtubed** [UnderscoreKilburn/repentance-issues#1205]
https://clips.twitch.tv/FreezingDarkWombatDatBoi-nvbZZp-VCv9_R7O9
https://clips.twitch.tv/AbstemiousEvilPuddingTebowing-ejEeq8g0SEz3msKT

I have been unable to reproduce this anomaly even on this seed with the same items.
As you can see, for some strange reason genesis didnt spawn a ladder back to the floor but instead a trapdoor, thus requiring the chest floor be done again.

**Comment by ZMBanshee** [comment]
There was recently an issue in between 1.7.9 and 1.7.9a that allowed Genesis to do this, but it's supposed to be fixed now. If you ever see this happen again in the future please do comment here, right now I'm not totally sure if this was simply recorded between these updates or if the player hadn't gotten the followup patch.

**Comment by bathtubed** [comment]
Okay, looks like this was pre 1.79a, but I'll point out that patch included no reference to this fix so I assumed it wasn't changed.

Thanks
