### ISSUE TITLE
mega mush oddities

### ISSUE THREAD

**Issue by Lonrite** [UnderscoreKilburn/repentance-issues#1224]
works in a weird way visulas-wise on t laz, most noticeable in downpour/dross/flooded caves

dunno if its weird as other chars on these floors though, haven't gotten around to testing it

also i'm p sure it can still softlock you if you use a pickup while it's active

**Comment by ZMBanshee** [comment]
About the softlock -  all you need to do is have flight, and then pills will break it like it used to. There could be other obscure ways, but that's the most easily reproducible one.

**Comment by Lonrite** [comment]
> About the softlock - all you need to do is have flight, and then pills will break it like it used to. There could be other obscure ways, but that's the most easily reproducible one.

ah I didn't know the exact scenario, that's good to know.

also i initially wanted to mention that it has strange visuals as T Laz but forgor, lemme edit it 1 sec

**Comment by ZMBanshee** [comment]
The softlock should be fixed soon and the other issues are mentioned elsewhere, so I'm going to close this one when the patch comes out.
