### ISSUE TITLE
more epiphora info

### ISSUE THREAD

**Issue by Lonrite** [UnderscoreKilburn/repentance-issues#1234]
resets when entering boss rooms which is inconsistent with how it doesn't reset upon entering a new floor or taking items

also i still think it should be more similar to dead eye where the tear buff doesn't instantly reset if you mess up

the boss room reset thing is probably a duplicate so ig just lock it if that's the cose

**Comment by ZMBanshee** [comment]
Duplicate of https://github.com/UnderscoreKilburn/repentance-issues/issues/839
