### ISSUE TITLE
Enemies dying upon reaching 0 hp isn't true for every ways of dealing damage.

### ISSUE THREAD

**Issue by Guillotine-221** [UnderscoreKilburn/repentance-issues#1250]
For example, i killed gurgle with a single use of blood rights but when i try to kill it with tears that deal exactly 8.00 damage(Isaac with cricket's head + 2 meat!s), it takes 6 shots instead of 5.

**Comment by Rchardon** [comment]
It's because the stat is rounded and doesn't deal exactly 8 damage every shots... If you test with the dummy you can see that 5 shots deals 39.98 damage and not 40

![Capture](https://user-images.githubusercontent.com/33094562/202871830-a67f1001-7855-4bfb-bb5b-6201940d68dd.PNG)
