### ISSUE TITLE
firing tech 2 as the soul then switching to the forgotten causes it to fire in that direction until swapping back to the soul

### ISSUE THREAD

**Issue by GumdropTheGummyBee** [UnderscoreKilburn/repentance-issues#1253]
title says it all, should be incredibly easy to replicate assuming i don't have any mods affecting it (which i'm 99% sure i don't).
edit: it also works vice versa, and ends if you go to a new room

**Comment by ZMBanshee** [comment]
Duplicate of https://github.com/UnderscoreKilburn/repentance-issues/issues/314
