### ISSUE TITLE
New Emperor? Softlock

### ISSUE THREAD

**Issue by MashSlyferiux** [UnderscoreKilburn/repentance-issues#1274]
Not sure if you are already working on it but if you use Reverse Emperor card in a Special Shop (the one spawned by the Member Card) you will be sealed in a loop only breakable with another teleport tool, switching room between the two indefinitely

**Comment by ZMBanshee** [comment]
Probably a duplicate of https://github.com/UnderscoreKilburn/repentance-issues/issues/741 but either way it's not happening for me, maybe there's something more to it?
