### ISSUE TITLE
Spike Rocks

### ISSUE THREAD

**Issue by Lonrite** [UnderscoreKilburn/repentance-issues#1278]
i get that it's probably intended the hitbox is larger than the normal rock but sometimes it's really bullshit, especially in this womb room when you try to pick something up or that Sheol room with multiple spike rocks on entrance from left and right side (that one is unfair with J&E)

idk how you can tweak the hitbox to be more intuitive but still, might be impossible entirely but still posting just in case lol.

![image](https://user-images.githubusercontent.com/74597482/204085716-777a1dcf-1b26-4d16-92bd-64684a2dbc72.png)

**Comment by luni3359** [comment]
It's not intuitive at all
