### ISSUE TITLE
All buyable items in the shop disappear when you buy an item with store credit + lost/t lost

### ISSUE THREAD

**Issue by Rchardon** [UnderscoreKilburn/repentance-issues#130]

**Comment by Rchardon** [comment]
And maybe all kind of lost forms

**Comment by ZMBanshee** [comment]
I'm aware that this bug once existed but I cannot reproduce it now. Are you sure it happens in the current version?

**Comment by Rchardon** [comment]
Looks like it has been fixed before, don't remember seeing it in a patch notes
