### ISSUE TITLE
Un-blacklist Bag of Crafting from daily runs

### ISSUE THREAD

**Issue by sscolon** [UnderscoreKilburn/repentance-issues#1319]
Cool G made a post about how Spindown could just skip past other blacklisted items, the same could be applied to Bag of Crafting, if Spindown gets un-blacklisted

**Comment by ZMBanshee** [comment]
I think this is a Spindown Dice situation where it just doesn't respect the daily blacklist. Obviously it could be updated to do so at some point if people actually want it there (it would surprise me), but that's the reason it's out currently.
