### ISSUE TITLE
non duplicated room changes

### ISSUE THREAD

**Issue by Zamiell** [UnderscoreKilburn/repentance-issues#133]
womb/utero/scarred #391 
womb/utero/scarred #383

**Comment by Zamiell** [comment]
womb/utero/scarred #388 doesn't seem to be marked as difficulty 0 in all versions

**Comment by Zamiell** [comment]
womb/utero/scarred #416 doesn't seem to be marked as difficulty 0 in all versions

**Comment by Zamiell** [comment]
womb/utero/scarred #424 doesn't seem to be marked as difficulty 0 in all versions

**Comment by Zamiell** [comment]
i spoke with kilburn earlier today and he said that this isn't intended, can you elaborate on why you think it is?

**Comment by ZMBanshee** [comment]
I know you spoke with him about it, but those difficulty 0 rooms are actually disabled rooms. What basically happened is that Leather disabled certain rooms on certain floors to give the floor alts more identity, usually in an attempt to make certain enemies feel more exclusive.

**Comment by Zamiell** [comment]
ok, but kilburn seems to agree that any room changes should be propagated to the other rooms, even if the other rooms are intended to be disabled for the time being, so what you explained only partially addresses this issue

**Comment by Zamiell** [comment]
otherwise, if the rooms are decided to be used again, then they would be out of sync
