### ISSUE TITLE
Alternate Path Doors Keep Closing (Bug)

### ISSUE THREAD

**Issue by Kbz2001** [UnderscoreKilburn/repentance-issues#1353]
I was playing a run as Tainted Forgotten and I noticed some strange functionality going on with the door throughout the alternate path. For example, I would bomb the door to the Mines and open it but every time I left the room the door would shut again. This wasn't a big issue since I had more bombs. However, this bug was game breaking when I got to the flesh door at the end of the Mausoleum. I shot the knife into the door to open it and went into a Devil deal. Upon exiting the Devil deal the door was closed again but my knife was consumed. I am now forced to go down into the Womb instead of continuing the alt path. I haven't gone down into the Womb yet, I was wondering if this bug gets fixed can I somehow still possibly continue my alt path run? I really don't want to redo it all.

**Comment by ZMBanshee** [comment]
There should be a hotfix out for this now. It will not retroactively fix the bug, however, meaning it will only help for future runs.
