### ISSUE TITLE
Mucormycosis tears that go through Multidimensional Baby grow to absurdly enormous size when attached to an enemy.

### ISSUE THREAD

**Issue by BlindTheBoundDemon** [UnderscoreKilburn/repentance-issues#1369]
I'm guessing the same will happen with Explosivo tears.

**Comment by ZMBanshee** [comment]
https://user-images.githubusercontent.com/13712144/206555583-668e9c9b-7fe5-4bde-ae94-4d0b57a6bc5c.mp4

I'm not seeing anything particularly unusual here.

**Comment by BlindTheBoundDemon** [comment]
odd. maybe there was another item that also contributed to this interaction... Well... I don't think I'm able to recreate it now so ¯\_(ツ)_/¯
