### ISSUE TITLE
Golden Penny

### ISSUE THREAD

**Issue by Lonrite** [UnderscoreKilburn/repentance-issues#1386]
doesn't work properly with bag of crafting

**Comment by ZMBanshee** [comment]
What?

**Comment by Lonrite** [comment]
> What?

wait nevermind i'm a dumbass, i forgot that golden penny is considered as a separate entity for bag of crafting and not just a regular penny.

at first the point of my post was that it doesn't respawn once you pick it up but it makes sense to me now since i remembered it's a higher quality pickup than a normal penny lol

false alarm moment
