### ISSUE TITLE
Fruit Cake proccing Sulfurid Acid doesn't destroy key blocks.

### ISSUE THREAD

**Issue by ghost** [UnderscoreKilburn/repentance-issues#1400]
Since Repentance Sulfurid Acid is also able to destroy key blocks, however it seems that proccing the effect of Sulfurid Acid through Fruit Cake isn't able to do so.

**Comment by ez-duke** [comment]
It was changed in 1.7.5
- Fixed lock blocks being breakable by Notched Axe, Sulfuric Acid, and other rock breaking effects (they are supposed to be breakable only by bombs + Broken Padlock)

**Comment by ghost** [comment]
Ahh I see, so that effect was unintended all along. Thanks for the heads up!
