### ISSUE TITLE
While being considered as a familiar by Box of Friends (preventing a Devil Baby to spawn), Box of Friends does not duplicate Strawman.

### ISSUE THREAD

**Issue by YazawaAkio** [UnderscoreKilburn/repentance-issues#1418]

**Comment by Lonrite** [comment]
![lol](https://github.com/UnderscoreKilburn/repentance-issues/assets/74597482/50150a79-c0e0-483b-b3a2-5bbbda52e98f)

intruder makes box of friends kinda worthless on T Lost early game where you don't really have many familiars

**Comment by Rchardon** [comment]
I guess this has been fixed by putting the uniquefamiliar tag instead of making it able to duplicate

**Comment by Lonrite** [comment]
> I guess this has been fixed by putting the uniquefamiliar tag instead of making it able to duplicate

kiiiiiiiiiiiiinda, lol.

I've had it happen recently but not 100% sure what causes it doe

**Comment by Lonrite** [comment]
https://www.twitch.tv/lonerite_/clip/ResourcefulColdBatteryCeilingCat--168NYvyaXCsnTHg

made a clip of this occuring ( latest build )

here's the seed just in case: SQ06 D0P1

**Comment by Rchardon** [comment]
@Lonerite reopen another ticket because this is not related to strawman and the ticket is closed
