### ISSUE TITLE
 Pay to Play makes chests go invisible when they contain an item

### ISSUE THREAD

**Issue by ghost** [UnderscoreKilburn/repentance-issues#1440]
When opening a golden chest while having Pay to Play, the chest will become invisible when it contains a pedestal item.

**Comment by ZMBanshee** [comment]
![20221218182829_1](https://user-images.githubusercontent.com/13712144/208327660-6bc19605-0ca7-4820-bb2a-71e15a8cc2fa.jpg)
Looks okay to me. Make sure it happens without any mods on. If one of your mods changes pedestal appearances it may not have been updated to have the Pay to Play chest sprite on its sheet, hence why it would be invisible for you.

**Comment by ghost** [comment]
> 

Oh damn so this really comes down to a mod then, thanks a lot for clarifying and sorry for the post in that case!
