### ISSUE TITLE
Frame-Perfect FMN dissolving 

### ISSUE THREAD

**Issue by Lonrite** [UnderscoreKilburn/repentance-issues#1441]
if you press spacebar at the perfect frame while room transitioning (somewhere in that timeline) FMN will just be gone out of your slot without getting used. same applies to R key apparently

https://user-images.githubusercontent.com/74597482/208319571-046832b0-2ba0-46aa-8639-ff4f98684b2e.mp4

**Comment by ZMBanshee** [comment]
Duplicate of https://github.com/UnderscoreKilburn/repentance-issues/issues/923
