### ISSUE TITLE
Delirious insanity

### ISSUE THREAD

**Issue by Lonrite** [UnderscoreKilburn/repentance-issues#1481]
can softlock you during Mega Satan fight

this is an old bug and I knew about it for a while but i don't think it's ever been reported here

![softlock1](https://user-images.githubusercontent.com/74597482/209477924-32600eb9-834a-47f9-a2fd-cc5f31f7d364.PNG)
![softlock2](https://user-images.githubusercontent.com/74597482/209477927-877c7613-5678-4d5c-8e52-21f0fcdcdad7.PNG)

**Comment by ZMBanshee** [comment]
Very likely caused by https://github.com/UnderscoreKilburn/repentance-issues/issues/299 

For now I'll label this as a duplicate, simply using Delirious in Mega Satan's fight doesn't seem to cause issues by itself. If the issue still occurs after the other one is fixed I'll reopen this one.
