### ISSUE TITLE
Book of Virtues doesn't work with some pocket actives

### ISSUE THREAD

**Issue by HDMonster1** [UnderscoreKilburn/repentance-issues#1588]
Apparently it works with TBethany's Lemegeton, TCain's Bag of Crafting, TJacob's Anima Sola and TEve's Sumptorium... 

...buuuuut doesn't work with TLazarus, TApollyon's Abyss, TMag's Yum Heart and TJudas' Dark Arts. 
Please fix.

**Comment by ZMBanshee** [comment]
Duplicate of https://github.com/UnderscoreKilburn/repentance-issues/issues/1466
