### ISSUE TITLE
Lil Loki isn't part of Conjoined transformation

### ISSUE THREAD

**Issue by Rchardon** [UnderscoreKilburn/repentance-issues#159]

**Comment by ZMBanshee** [comment]
Conjoined is a bit arbitrary. Most of the familiars based on bosses don't count towards the transformation (such as Little Gish, Lil Monstro, or Little C.H.A.D.), and Lil Loki is among those.

It's a little inconsistent considering Little Steven *does* count, but truth be told I'm not actually sure the transformation needs to be more common in Repentance. Perhaps some arbitrary limitations are a good thing for it, lest we end up in a situation where we're just slapping the conjoined tag on almost every familiar in the game. The rules could at least be consistent, though, so maybe this could be tweaked in some way at some point.

**Comment by Rchardon** [comment]
Well the familiar itself isn't very good so at least being part of Conjoined could buff him a little bit but i agree the transfo is already common so idk

**Comment by ghost** [comment]
I think that now that lil loki is in another pool (the ultra secret room pool) he should at least be a conjoined part.

**Comment by Rchardon** [comment]
It is done boys, i'll close it
