### ISSUE TITLE
Daily Run not working

### ISSUE THREAD

**Issue by Lonrite** [UnderscoreKilburn/repentance-issues#1612]
not sure how else to notify _Kil about this without directly DMing him so here I am

february 2nd is the only day in the year that never works in AB (groundhog curated daily), works fine in AB+ and Rep but never ab for some reason
![notworking](https://user-images.githubusercontent.com/74597482/216297700-0ffe8c4c-1a76-4d15-a898-698767cce501.PNG)

**Comment by Lonrite** [comment]
yesterday's AB was a nigh-trainwreck so I wouldn't even mind waiting til' this gets fixed lol

**Comment by ZMBanshee** [comment]
This tracker is for Repentance. Afterbirth support is discontinued.

**Comment by Lonrite** [comment]
well hopefully it'll be fixed by the next year COPIUM
