### ISSUE TITLE
Bringing NS Switch up to date on balance changes from PC

### ISSUE THREAD

**Issue by plbpietrz** [UnderscoreKilburn/repentance-issues#1636]
Hi,

wanted to ask if there is any timeframe for the balance changes from PC to make their way onto the Switch?

P.S.
Great game! :)

**Comment by ZMBanshee** [comment]
The console ports aren't handled by the same people developing the game itself. This tracker is meant for reporting bugs/issues with the current game version or feature suggestions.

I wish I could answer your question, but as of now there doesn't seem to be a confirmed timeframe for porting the updates. You can try contacting them by emailing isaac@nicalis.com

Glad you're enjoying the game.
