### ISSUE TITLE
Vibrant / Dim bulb disparity 

### ISSUE THREAD

**Issue by Lonrite** [UnderscoreKilburn/repentance-issues#1647]
1) if vibrant bulb gets gulped, most of the time you don't even get any stat ups even when your active item is fully rejuvenated

2) dim bulb is completely opposite in that it works no matter what even if your active has charges (as long as it's gulped)

**Comment by ZMBanshee** [comment]
Can you show me how to replicate this? It seems fine to me.

**Comment by Lonrite** [comment]
> Can you show me how to replicate this? It seems fine to me.

well, i tried at least — https://youtu.be/IEKX5L4yfpE

it's kinda inconsistent and also, i was gonna say "maybe it's just because of debug 8 being a bit fucky" but then again, the reason I even made this post in the first place is that because I noticed Vibrant Bulb acting very strange when gulped in AB+ daily, and then decided to test in Rep afterwards

**Comment by ZMBanshee** [comment]
It was working correctly when you weren't using debug 8.

**Comment by Lonrite** [comment]
> It was working correctly when you weren't using debug 8.

well I hope both of these do, that's good then. it was buggy as heck for me in AB+ when gulped but i trust ya'll that it's fine in rep. ig debug 8 confused me
