### ISSUE TITLE
mini* map icons

### ISSUE THREAD

**Issue by Lonrite** [UnderscoreKilburn/repentance-issues#1675]
some things like mind should always be shown on the mini map i think (idr if i mentioned it before but ye)

**Comment by CoolG0101** [comment]
some things like mind should always be shown on the mini map i think (idr if i mentioned it before but ye)

**Comment by ZMBanshee** [comment]
If you mean an icon under the map, The Mind does have an icon.

**Comment by Lonrite** [comment]
> If you mean an icon under the map, The Mind does have an icon.

oh damn, I forgot about that entirely. that's nice actually
