### ISSUE TITLE
SFX and Visual glitch / bug

### ISSUE THREAD

**Issue by kode-tar-gz** [UnderscoreKilburn/repentance-issues#1677]
I just bought repentance and all other DLCs, although i had been playing rebirth for a while. As soon as i opened it, i noticed there were no sfx for when i moved in the menu (clicking up / down in the menu usually makes a paper-like sound). Then, when i started a game, a lot of sfx were missing. Sounds of rooms opening and closing, etc. Some monsters made no sound at all. Then i noticed some pretty major visual glitches. Especially when I picked up an item, isaac's body would disappear and all that would remain would be his head, although very glitched itself. Coins are basically invisible, sometimes other items are invisible. Some monsters are invisible and all monsters have a visual glitch when they spawn. Also when i enter a sacrifice room the game completely crashes. I tried to reinstall the game, 3 times. Didn't work. Checked for game file validity etc, didn't fix it either. Deleted all game files including my saves, then installed it again. Didn't work. I basically can't play the game. I'm on windows 10

**Comment by kode-tar-gz** [comment]
update: the game also crashes when i enter the womb and the black room (the one that doesnt have spikes on the door, only blood). a lot of bosses dont have any boss music. buttons are invisible. a few monsters are invisible and dont make any sound.

**Comment by Rchardon** [comment]
That is the most vague problem i've seen. Also this github page is made for bugs in the game, not for problems on your side. There are Steam Forums or the official Isaac Discord for that

**Comment by kode-tar-gz** [comment]
> That is the most vague problem i've seen. Also this github page is made for bugs in the game, not for problems on your side. There are Steam Forums or the official Isaac Discord for that

I've already tried steam forum and discord. Both told me to come here. Every single other game runs perfectly in my pc. Rebirth ran perfectly and so did antibirth. This only started happening after I installed repentance.

**Comment by Rchardon** [comment]
I hope you uninstalled Antibirth before installing Repentance

**Comment by kode-tar-gz** [comment]
I hadn't, I didn't think that would be a problem. But i uninstalled antibirth and isaac itself, then reinstalled isaac and the problem persisted. Also, I just installed the game on a different computer of mine that did not have antibirth at any point in time, and the same exact problems are present. I'll probably have to refund the game and crack it at this point

**Comment by ZMBanshee** [comment]
The fact that this is happening to you on different computers and also only with DLC enabled makes me think this is a problem with a workshop mod you're subscribed to, since base Rebirth doesn't have workshop support. Make sure you aren't subscribed to any mods on the workshop. Unsubscribe, load the game to let it unsubscribe, then restart the game and see if it works better.
