### ISSUE TITLE
Bat Wing was mistakenly given the "nogreed" tag in V1.7.9 in place of Ice Cube

### ISSUE THREAD

**Issue by SuportSnek** [UnderscoreKilburn/repentance-issues#1713]
In V1.7.9, a number of trinkets were given the "nogreed" tag. Among these included the Bat Wing trinket, which has an entity ID of 5.350.118. This item works perfectly fine in Greed Mode. The trinket that was almost certainly meant to be removed was Ice Cube, which doesn't do anything in Greed mode, and has an ID of 5.350.188.

So, all that has to be done is remove the "nogreed" tag from Bat Wing, and add it to Ice Cube.

**Comment by Rchardon** [comment]
You're months late, we are in 1.7.9b and this is already fixed, see #1123

**Comment by SuportSnek** [comment]
Oh, I totally missed that Rchardon. Sorry about that!
