### ISSUE TITLE
Instant hit room

### ISSUE THREAD

**Issue by ERRRR0R** [UnderscoreKilburn/repentance-issues#1766]
Flooded Caves Default 555. If you enter from side, blue fly can instantly kill drowned charged right by the entrance and you get unavoidable hit

**Comment by Lonrite** [comment]
i recently encountered a room which I don't think I ever saw before in years, although admittedly it wasn't in Repentance (so idk if it still exists)

it has a begotten tied to room entrance door, like 2 tiles away from the player - very reminiscent to rooms with spikes in front of entrance

if you move even an inch when entering you get hit pretty much - it's an extraordinarily rare room but still
