### ISSUE TITLE
rare crash

### ISSUE THREAD

**Issue by Lonrite** [UnderscoreKilburn/repentance-issues#1769]
sometimes the game crashes after the chest ending if you watch the credits fully and out of fullscreen, happens without mods very rarely

**Comment by ZMBanshee** [comment]
Could you attach a dmp file if one was produced by this crash? Make sure it's actually from that crash, of course.

**Comment by Lonrite** [comment]
> Could you attach a dmp file if one was produced by this crash? Make sure it's actually from that crash, of course.

not sure that'd be plausible here, I might as well just close the issue lol
