### ISSUE TITLE
The Moon dupe

### ISSUE THREAD

**Issue by retueZe** [UnderscoreKilburn/repentance-issues#1802]
Seed: SZ6RNEA6
Char: Judas (0 unlocks, 0 achievements)
Mods: none
DLCs: all
Version: 1.7.8a

After killing the boss, I got the item dropping me some cards (I just remember its description "collect them all"). I picked The Moon up and used it, got teleported to a secret room, everything is fine. But then I entered the boss room and The Moon was still there, i.e. duped. The cards changed their order, by the way. I used only The Moon, other cards weren't activated, and i don't know if they will dupe too or not.

To me it seems like on entering the boss room after the teleportation the pick up effect of this item is firing again (changed order of the cards, cards drop around the same position every time), because it got stuck somewhere inside the code, like troll bombs from chests spawning over and over again after you entered the room and didn't let them explode. But it obviously shouldn't work that way. In my case there was only 1 secret room, but you potentially can explore all of them using this bug and only 1 card. I think, because of its nature, this will work also with The Hermit, The Emperor, etc.

**Comment by Rchardon** [comment]
Did you have the endless nameless trinket ?

**Comment by retueZe** [comment]
> Did you have the endless nameless trinket ?

I haven't even noticed it. What a newbie negligence...
