### ISSUE TITLE
Battery Pack is bugged when rolling into it with Soul of Isaac

### ISSUE THREAD

**Issue by ghost** [UnderscoreKilburn/repentance-issues#1803]
If you reroll any item into Battery Pack by using a Soul of Isaac and then pick up the Battery Pack, it will have no effects. It does neither charge your item nor drop batteries in that case.

**Comment by ZMBanshee** [comment]
Currently tracking pickup and transformation related issues with Soul of Isaac items here https://github.com/UnderscoreKilburn/repentance-issues/issues/308
