### ISSUE TITLE
Using Undefined on the frame you enter the next room after exiting a special room cancels the teleport and makes you unable to move

### ISSUE THREAD

**Issue by Rchardon** [UnderscoreKilburn/repentance-issues#1820]
https://user-images.githubusercontent.com/33094562/228015004-fe1ce6c4-8cca-474c-aaac-0797bfa59359.mp4

**Comment by ZMBanshee** [comment]
Duplicate of https://github.com/UnderscoreKilburn/repentance-issues/issues/62
