### ISSUE TITLE
More Options + Pay to Win don't synergize correctly on most alt path floors

### ISSUE THREAD

**Issue by StoneyWagner** [UnderscoreKilburn/repentance-issues#1823]
This is because most of the "double t reroll" rooms have subtype 2 instead of 3. Ashpit, Mausoleum, Gehenna, and the Corpse do have subtype 3 for some of these rooms, but not the thin ones.

This also causes Pay to Win by itself to be unintentionally stronger on these floors by giving it a chance to spawn the "double t reroll" rooms without More Options.

**Comment by Rchardon** [comment]
Is it related to #1839 and is fixed too ?
