### ISSUE TITLE
Cursed Room doors still deal NO damage with a certain speed

### ISSUE THREAD

**Issue by DO97** [UnderscoreKilburn/repentance-issues#1830]
https://www.reddit.com/r/bindingofisaac/comments/11p8a2j/if_you_are_fast_enough_you_can_bypass_curse_room/?utm_source=share&utm_medium=android_app&utm_name=androidcss&utm_term=1&utm_content=share_button

Most (if not all) people notice this bug with a speed of 1.8 or 2.0 and, despite some corrections in the past, it is still present in the game.

**Comment by ZMBanshee** [comment]
Duplicate of https://github.com/UnderscoreKilburn/repentance-issues/issues/80
