### ISSUE TITLE
Eye of Guppy showed me Head of Keeper but upon blowing the keeper up, it didn't spawn

### ISSUE THREAD

**Issue by Bonfo1** [UnderscoreKilburn/repentance-issues#184]
No mods on, I was doing the daily run

https://user-images.githubusercontent.com/94471017/142779821-79447483-06cb-44c3-8115-1b3401cad4c7.mp4

**Comment by Neonomi** [comment]
For some reason this usually happens when you extinguishing the fireplace https://clips.twitch.tv/BombasticNiceAlmondCharlieBitMe-Vp7avhn5vREReuCi

Also fireplaces can lead to desync on netstart coop, maybe same issue?
