### ISSUE TITLE
Tainted Lazarus with birthright can't revive with Judas' Shadow, Ankh and Missing poster

### ISSUE THREAD

**Issue by Rchardon** [UnderscoreKilburn/repentance-issues#1851]
https://www.twitch.tv/phastos/clip/ColorfulBlatantReindeerPanicVis-HQT1Wo8CRikYY93K

1up, lazarus rags and Dead cat work tho

**Comment by ZMBanshee** [comment]
Duplicate of https://github.com/UnderscoreKilburn/repentance-issues/issues/937
