### ISSUE TITLE
My game crashes when I enter the living room

### ISSUE THREAD

**Issue by Droep** [UnderscoreKilburn/repentance-issues#186]
As the title, I have tried lots of times and even uninstalled my game, I found that it maybe because of the TV.
When I spawn the TV(960.4), my game crashes again. But that didn't happen before v1.7.5, I can't find out the reason. I posted it on steam and asked it on Discord, but nobody knows what happened. Because of this bug, I can't unlock any tainted characters, that makes me frustrated.

Here's a list of what I tried:

·Unsubscribe all my mods
·Uninstall my game and install it again
·Subscribe a mod that changes the TV texture

Please give me some advice or fix this bug, it has troubled me for many days. I'll send my crash log for you too. Thanks a lot!
[isaacv1.7.6.0000-20211121-145006-1876-2156.txt](https://github.com/UnderscoreKilburn/repentance-issues/files/7579087/isaacv1.7.6.0000-20211121-145006-1876-2156.txt)

(If it's difficult to read my mail, I'm sorry for my bad English cause that's not my native language.)

**Comment by ZMBanshee** [comment]
Hi, this is old. I've not heard of this happening to someone since then, so I'm going to ask that you reopen this if it still occurs, thank you.
