### ISSUE TITLE
Hornfell layout crash

### ISSUE THREAD

**Issue by Lonrite** [UnderscoreKilburn/repentance-issues#1913]
might not be super consistent but this layout seems to crash the game

seed in case required: 8E1S 9CT1

![crash](https://github.com/UnderscoreKilburn/repentance-issues/assets/74597482/f3bd47fa-a910-41d2-b9fa-5cc70956ff1c)

**Comment by Lonrite** [comment]
might be c section related if they try to go into the spawn door he went or something, no clue but yeah it does occur

**Comment by ZMBanshee** [comment]
I'm going to assume it's this https://github.com/UnderscoreKilburn/repentance-issues/issues/585

**Comment by Lonrite** [comment]
ye
