### ISSUE TITLE
fresh massive bug that occurred in a daily

### ISSUE THREAD

**Issue by Lonrite** [UnderscoreKilburn/repentance-issues#1914]
not really fresh i had it happen before, i've never figured out the cause completely but pretty sure this occurs if you use soul of isaac multiple times on a pedestal

still insanely bullshit though

basically look at my key count and items :I
![wow](https://github.com/UnderscoreKilburn/repentance-issues/assets/74597482/91f935f4-5c21-40a5-baf0-a9116bbf1961)

**Comment by lonerite01810** [comment]
yeah no i'm out not submitting this insulting POS

**Comment by lonerite01810** [comment]
yeah no i'm out not submitting that insulting POS

**Comment by lonerite01810** [comment]
yeah no i'm out not submitting that insulting POS, it was nearly 19k on boss rush start but i don't care for these kind of runs when stuff like that happens lol

**Comment by lonerite01810** [comment]
yeah no i'm out not submitting that insulting POS, it was nearly 19k on boss rush start [before i started getting hit and losing strawman in it] but i don't care for these kind of runs when stuff like that happens lol

**Comment by Lonrite** [comment]
yeah no i'm out not submitting that insulting POS, it was nearly 19k on boss rush start [before i started getting hit and losing strawman inside of it] but i don't care for these kind of runs when stuff like that happens lol

**Comment by ZMBanshee** [comment]
Tracking issues with items not giving all effects with Soul of Isaac here https://github.com/UnderscoreKilburn/repentance-issues/issues/308
