### ISSUE TITLE
chaos card bugs out alt path

### ISSUE THREAD

**Issue by Lonrite** [UnderscoreKilburn/repentance-issues#1915]
if you throw chaos card in the direction of the door not only does it only destroy it partly [you need 1 more bomb], it makes some rock breaking sound and it's impossible to use the card afterwards even if you have pressed all 3 buttons, with having flight being the only way out

![nice](https://github.com/UnderscoreKilburn/repentance-issues/assets/74597482/066fff18-b9cd-4973-9ad1-63c880dc8da4)

**Comment by Lonrite** [comment]
btw more of a side thing but the path being scripted to always be 100% made doesn't always make sense since half of the time you just bomb the door 2 times as the character, without even pressing the buttons - yet the path is still existing after you escape

**Comment by lonerite01810** [comment]
gonna remake this without the "cart" typo

**Comment by Lonrite** [comment]
gonna remake this without the "card" typo
