### ISSUE TITLE
costumeSuffix for all Characters in Players.xml

### ISSUE THREAD

**Issue by KingLanky** [UnderscoreKilburn/repentance-issues#1917]
Suggestion to have a `costumeSuffix` defined for _all_ characters in Players.xml, with corresponding directories, for Mod compatibility.
This way costume-only mods would no longer have to edit Players.xml, and wouldn't conflict with each other.
e.g. [players.xml](https://github.com/UnderscoreKilburn/repentance-issues/files/12310975/players.txt)

**Comment by ZMBanshee** [comment]
Modding related issues/suggestions go here https://github.com/Meowlala/RepentanceAPIIssueTracker/issues
