### ISSUE TITLE
Siren is filled with bugs

### ISSUE THREAD

**Issue by Lonrite** [UnderscoreKilburn/repentance-issues#1922]
most obnoxious one being having cube of meat / ball of bandages [apparently even pretty fly orbitals] - if she charms them you're doomed to an instant hit with 0 way to avoid it

also using tp cards when she has charmed items of yours seems to always crash the game

most probably a known duplicate but posting it in case its not

**Comment by Rchardon** [comment]
Kinda similar to your #695

**Comment by Lonrite** [comment]
oh yeah, i'll just mention it there.
