### ISSUE TITLE
enormous daily run issue 

### ISSUE THREAD

**Issue by Lonrite** [UnderscoreKilburn/repentance-issues#1924]
if the game spawns a hatch inside dark room / chest on a Mega Satan goal while doing a daily run, you get sent to the next floor.

however, unlike Forget Me Now, your key pieces don't get restored so the only way to avoid it is run away from the starting room like your life depends on it [even that preemptively assumes you know in advance there's a hatch]

lost out on 6666 points on a nearly flawless AB daily because of that, like what is this

99.9% sure it works fine with FMN in all AB / + and Rep but not with hatches like that so yeah.

![are you serious](https://github.com/UnderscoreKilburn/repentance-issues/assets/74597482/b4195fd1-5847-4ab7-aa48-99936351671a)

**Comment by ZMBanshee** [comment]
This is a Repentance bug tracker, so don't post bugs that don't apply to it here.
