### ISSUE TITLE
rainbow baby

### ISSUE THREAD

**Issue by Lonrite** [UnderscoreKilburn/repentance-issues#1925]
would be neat if it had some in-real time rainbow animation on the baby itself [since it's rainbow on the item tracker but in-game it's just pink-ish]

**Comment by Lonrite** [comment]
well, to be correct it's not really rainbow on the item tracker but it has rainbow surrounding it

**Comment by Lonrite** [comment]
it would work similarly to rainbow champions / golden trinkets / dogma item animation / lil' steven tear basically, if not the same (or just be a rainbow sprite, not even an animation effect necessarily)

**Comment by Lonrite** [comment]
also lil' bro should be quality 2 💀

**Comment by Rchardon** [comment]
You copied my idea #1800 bruh
Always remember to search in the github searchbar with keeywords

**Comment by lonerite01810** [comment]
> You copied my idea #1800 bruh Always remember to search in the github searchbar with keeywords

based idea but I never copied anything, why would I dig up old necro threads on a game that's mostly done with updates at these point

I just post these 4 fun as food for thought sometimes whenever I feell ike it

**Comment by Lonrite** [comment]
> You copied my idea #1800 bruh Always remember to search in the github searchbar with keeywords

based idea but I never copied anything, why would I dig up old necro threads on a game that's mostly done with updates at these point

I just post these 4 fun as food for thought sometimes whenever I feel ike it, but it is a funny coincidence that we both had the same idea lol
