### ISSUE TITLE
gello+parasite+jacobs ladder(bug)

### ISSUE THREAD

**Issue by FleXo0001** [UnderscoreKilburn/repentance-issues#1927]
https://github.com/UnderscoreKilburn/repentance-issues/assets/143740856/309d58f5-14fe-4bd6-b6ec-71becf750ea7

**Comment by FleXo0001** [comment]
https://github.com/UnderscoreKilburn/repentance-issues/assets/143740856/20d502b3-f9e9-4206-9a98-058e5e99e572

another one

**Comment by ZMBanshee** [comment]
Tracking this at https://github.com/UnderscoreKilburn/repentance-issues/issues/1408 (we do know what causes it)
