### ISSUE TITLE
re-lax / card against humanity with brimstone

### ISSUE THREAD

**Issue by Lonrite** [UnderscoreKilburn/repentance-issues#1938]
![2 hits](https://github.com/UnderscoreKilburn/repentance-issues/assets/74597482/88954890-aa84-4e8d-b4e6-2e1fd6c974fa)

Something like this should never ever be possible and you should still be able to destroy poops with brim if they're in close vicinity (or at least just get out of it)

for card against humanity I just meant a situation where you don't destroy part of the poops in time and get trapped, which usually happens in smaller rooms

(pretty sure that still happens in Rep hence posting this here)

**Comment by ZMBanshee** [comment]
It doesn't. You could at least check first.

**Comment by Lonrite** [comment]
> It doesn't. You could at least check first.

usually (by usually i mean like 70% of the time) I do try to check these things but in this case I had so little faith it was touched i didn't even bother.

but yeah apologies, I tested and you're right thankfully it's not a problem anymore.

On that thread of button spawning a hatch and removing 2 key pieces I also wanted to test it in Repentance's daily in practice before posting, but couldn't figure out how to do it, so I just went along with it

considering _Kil is gone I try to be less careful with these now but ofc i still check for stuff like duplicates (i nearly posted about divine intervention T lost again for example)
