### ISSUE TITLE
Bethany and J+E have inconsistent portrait color on the inside.

### ISSUE THREAD

**Issue by HyperInvox** [UnderscoreKilburn/repentance-issues#198]
Bethany and Jacob + Esau's portraits both are colored in with a color inconsistent with the rest of the pre-rep character portraits.

![literally unplayabel](https://user-images.githubusercontent.com/64395786/143200158-326febdc-a090-4ece-93f2-fbf2f92a6c94.png)
(ignore Job peeking in on the right hes photobombing get him out get him ou NO MODDED CHRACTERS ALOUD!!)

**Comment by UnderscoreKilburn** [comment]
Poor Job he just wanted his 15 minutes of fame 😔
