### ISSUE TITLE
Fruity Plum shoots when a Mine Crafter barrel is nearby

### ISSUE THREAD

**Issue by itsrekhab** [UnderscoreKilburn/repentance-issues#2027]
not a bug per se, but it led me to a lot of unnecessary (and I guess avoidable) dmg taken. either make the plum not react to the barrel or make her tears not able to collide with the barrel

**Comment by ZMBanshee** [comment]
Upon testing this, it doesn't seem like Fruity Plum shoots at barrels, though her tears can destroy the barrel (this is also the case with other familiars so probably not a bug).
