### ISSUE TITLE
rainbow champion lover cheating on u

### ISSUE THREAD

**Issue by Lonrite** [UnderscoreKilburn/repentance-issues#2061]
if you befriend rainbow champion lil' bro will keep pulling you in which is pretty annoying, definitely unintended

**Comment by ZMBanshee** [comment]
Duplicate of https://github.com/UnderscoreKilburn/repentance-issues/issues/1090

**Comment by Lonrite** [comment]
oh ye true lol, not like that matters much tbh since I doubt any bugs are getting fixed but w/e
