### ISSUE TITLE
Box of Friends usability

### ISSUE THREAD

**Issue by Lonrite** [UnderscoreKilburn/repentance-issues#2071]
this is an old bug since AB, it still persists in Rep just slightly differently

if you have 2 key pieces and nothing else Demon Baby just refuses to spawn

in AB you just get extra key pieces and in Rep dust animation plays and nothing happens

**Comment by Lonrite** [comment]
same goes for full Knife in Mother route btw, it really should get duplicated ( unlike the MS key )

**Comment by ZMBanshee** [comment]
That doesn't seem true, the Demon Baby spawned just fine for me with key/knife pieces. But there are other things that can cause that, like 1up, Lost Soul, Star of Bethlehem, and Strawman.

**Comment by ZMBanshee** [comment]
Kind of related to https://github.com/UnderscoreKilburn/repentance-issues/issues/1418 but if you find others that cause that problem aside from the ones I listed just comment them there

**Comment by Lonrite** [comment]
actually yeah you're right, now that I think about it I did use Box of Friends many times with key / knife pieces to make them work

anyways I think I figured out what happened - gonna post it in the other thread.

**Comment by Lonrite** [comment]
https://www.twitch.tv/lonerite_/clip/ResourcefulColdBatteryCeilingCat--168NYvyaXCsnTHg

made a clip of this occuring ( latest build )

here's the seed just in case: SQ06 D0P1
