### ISSUE TITLE
The chase sequence with Magdalene + Birthright

### ISSUE THREAD

**Issue by ButterSus** [UnderscoreKilburn/repentance-issues#2123]
Obtaining Knife Piece 2 during the chase sequence as Magdalene with Birthright and blue hearts causes any hearts exceeding the standard limit to disappear.

![image](https://github.com/user-attachments/assets/e998bdf9-5afe-4de7-aa5e-7578df168e6f)

**Comment by Rchardon** [comment]
Duplicate of #11
