### ISSUE TITLE
Greed machine issue in Repentance+

### ISSUE THREAD

**Issue by insan3d** [UnderscoreKilburn/repentance-issues#2127]
Hello.

Steam just screwed up with my saves again so I wiped all my saves on all of my PCs, disabled Cloud Sync, uninstalled Isaac, wiped all the leftover files, dowloaded the game again, ensured no Cloud Sync enabled ffs (obviously, no console or mods enabled too) and decided to go for a new file on new version.

On the fifth run I tried Greed mode and suprised what donation count did not increased (and jam risk percentage also). Didn't took screenshot before bossfight, but trust me, [here](https://www.dropbox.com/scl/fi/6fq2lfj44pg6jwhp7ewsa/20241120030444_1.jpg?rlkey=ry1ghaxumowi6nf53xg78ozor&st=xahnh7xa&dl=0) I spent all of my money on donation just like in real life — without any impact.

Players on Steam started to notice [the same issue](https://steamcommunity.com/app/250900/discussions/0/6330467073266896247/) too.

I would like to provide some useful info and logs for this issue to help with it resolution but have no idea what to collect.

UPD: replayed as Azazel, got Lilith unlock, but Greed machine still [tries](https://www.youtube.com/watch?v=loznIMT0WiE) to teach me a living lesson.

**Comment by Lonrite** [comment]
I mentioned this in the Repentance+ odditties thread, the greed dono machine is quite clunky in that iteration to say the least
