### ISSUE TITLE
Wavy Cap Game Crash

### ISSUE THREAD

**Issue by ProfGoat** [UnderscoreKilburn/repentance-issues#2135]
While playing local co-op on ps4, we tried using wavy cap and it immediately crashes the game every time. The person using wavy cap is azazel and has the fun guy transformation. Not sure what all is involved in causing the crash, but hopefully this can be fixed.
![PXL_20241125_004441919](https://github.com/user-attachments/assets/906f10bf-c0d2-465d-8d56-4fabe1161e94)

**Comment by ZMBanshee** [comment]
Duplicate of https://github.com/UnderscoreKilburn/repentance-issues/issues/1899
