### ISSUE TITLE
[REP+] Certain game's function skips Entity check (stops at ent->m_Parent) for T.Lilith Gello's C Section tears, causing game to crash

### ISSUE THREAD

**Issue by epfly6** [UnderscoreKilburn/repentance-issues#2145]
Description for reproduction:
1. Enter seed BEF3 A7MH
2. Start as Tainted Lilith in Hard Mode
3. Go to Treasure Room and take C Section
4. Go to the room with enemies and start shooting

Thanks to @Pezbi for providing initial details 
(for some reason T.Lilith Gello's C Section tears returns NULL for SpawnerEntity)

.dmp file included:
[isaacv1.9.7.6.J148-20241202-000104-52308-41992.dmp](https://github.com/user-attachments/files/17970369/isaacv1.9.7.6.J148-20241202-000104-52308-41992.dmp)

**Comment by ZMBanshee** [comment]
Just reproduced this crash with clots as well when they die. Explains a crash I had yesterday with Sumptorium and C Section.
