### ISSUE TITLE
Suggestion for the echo chamber nerf

### ISSUE THREAD

**Issue by Rchardon** [UnderscoreKilburn/repentance-issues#216]
I don't know if you got an idea so i propose one.
From an internet page i've read : "Echo chambers can create misinformation and distort a person’s perspective" 
Here is what i propose : 
Each time you use a card/pill/rune, you have a chance to reset Echo Chamber (chance increases each use) but also distort the screen or showing a stat (pickup stats included) with question marks (stats will be shown normally when echo chamber will be reset)

**Comment by ZMBanshee** [comment]
New rework for it is up, you can reopen this if you still want to suggest something different for it.
