### ISSUE TITLE
Bipolar Tech 0.5

### ISSUE THREAD

**Issue by Lonrite** [UnderscoreKilburn/repentance-issues#2168]
the item now has a chance to proc tear effects & such for 0 reason outta nowhere

![normal build](https://github.com/user-attachments/assets/b35eefc6-3ddf-4428-b0cf-a07d283a8632)

I don't really have anything that would make it act this way yet it did 2 times in a row lol

**Comment by ZMBanshee** [comment]
It was always supposed to have random effects sometimes, that was just broken in Rep for a while

**Comment by Lonrite** [comment]
> It was always supposed to have random effects sometimes, that was just broken in Rep for a while

wait really? 'Cause I've heard others mention it can do an explosion effect as well. If so that's a huge nerf lol, albeit a rare once since the effect barely procs

I wish it didn't at least self-hurt you ( dunno if it does as is I never quite got to testing it around )

**Comment by Lonrite** [comment]
> It was always supposed to have random effects sometimes, that was just broken in Rep for a while

1 of the prominent Nicalis ppl you might know tells me it's still intended though ( even after seeing this thread ), so I guess expect this to be fixed no matter what lol

**Comment by Lonrite** [comment]
worm trinkets stopped working in Rep+ btw with tech 0.5 which is def unintended 4sho

**Comment by ZMBanshee** [comment]
If it lost synergies that's definitely unintended yes. The lack of random effects is something I reported to them, they mysteriously went missing in some Rep patch. Though the old random effects on Tech.5 were just a set list of effects, like worm effects, Tiny Planet, and a couple of others. It seems like for this new version they might've just copied Fruit Cake's list?

**Comment by Lonrite** [comment]
> If it lost synergies that's definitely unintended yes. The lack of random effects is something I reported to them, they mysteriously went missing in some Rep patch. Though the old random effects on Tech.5 were just a set list of effects, like worm effects, Tiny Planet, and a couple of others. It seems like for this new version they might've just copied Fruit Cake's list?

i just hope no explosives are involved if it ever gets in, since tech 0.5 has been my #1 fav tech item for a long time now and it getting nerfed would be devastating.
