### ISSUE TITLE
Bosses take 20% less damage if you have item/consumable/trinket that creates a new char

### ISSUE THREAD

**Issue by Danial29** [UnderscoreKilburn/repentance-issues#217]
I don't know if it's a bug, posted it just in case
When you have/use Strawman/Found Soul/Soul of the Forgotten/Soul of Jacob and Esau/TLaz Birthright, bosses take 20% less damage from all sources. It works similarly in co-op, so I think it was overlooked in case of items, because it doesn't make much sense for items like Strawman or Soul of the Forgotten/JnE. 
![image](https://user-images.githubusercontent.com/95134927/143685314-ad280c36-f6ce-4d2b-8688-a6c33dae3e8a.png)
![image](https://user-images.githubusercontent.com/95134927/143685339-a7a6a17a-9467-47d5-ae32-61ef29cf3459.png)
![image](https://user-images.githubusercontent.com/95134927/143685355-dd959d90-a182-409a-ba5c-9777c00a0e45.png)

**Comment by ZMBanshee** [comment]
It's a bug yeah, it's meant for coop. Not that I really mind it affecting Found Soul, but the others certainly don't deserve it.

**Comment by AyyItsClarkster** [comment]
is this meant to apply to Tainted Laz' Birthright? The active form's damage is reduced by 20% and the non-active by 80%, is the main form supposed to deal full damage?
