### ISSUE TITLE
Tainted Lazarus while flipping cause crash if you have Yes Mother transformation

### ISSUE THREAD

**Issue by Neonomi** [UnderscoreKilburn/repentance-issues#234]
Same happening if you swap them
If you get transformation at first, crash only sometimes 

Tested with other transformations, seems ok

https://user-images.githubusercontent.com/94190069/143930014-7227ffec-28cf-47f9-a06d-52dced14a36d.mp4

**Comment by Neonomi** [comment]
Turns out, you don't even have to be risen

**Comment by ZMBanshee** [comment]
I think this is the cause of the seemingly random Flip crashes that got posted here before. Nice going figuring that one out.
