### ISSUE TITLE
Tainted keeper cannot complete Greedier mode

### ISSUE THREAD

**Issue by CooperLambaste** [UnderscoreKilburn/repentance-issues#249]
If you leave the main room, be it for checking treasuries or having to stop the horde of monsters, upon coming back to said room, enemies stop dropping coins, rendering the mode impossible to complete, since you are unable to purchase enough items.

**Comment by ZMBanshee** [comment]
Duplicate of https://github.com/UnderscoreKilburn/repentance-issues/issues/160
