### ISSUE TITLE
Multiple items and especially trinkets should have the nogreed item tag due to not doing anything in Greed Mode

### ISSUE THREAD

**Issue by AyyItsClarkster** [UnderscoreKilburn/repentance-issues#255]
These items and trinkets either do literally nothing, or practically nothing in Greed Mode, and so should have the nogreed item tag (almost all of these follow the same logic as other items that have the tag)

Items:
Contract from Below (Practically no room-clear rewards in Greed Mode)
Guppy's Tail (Practically no room-clear rewards in Greed Mode; arguable since it's still a Guppy item)
Mitre (Not relevant to Greed Mode)
Treasure Map (Doesn't reveal Secret Rooms so this is useless)
Death's List (No effect on wave spawns)
Duality (No effect in Greed Mode)
Glyph of Balance (No effect in Greed Mode other than I suppose +2 Soul Hearts, so it's arguable)
Poke Go (No effect on wave spawns)
Goat Head (Devil/Angel rooms are already guaranteed)
Voodoo Head (No effect in Greed Mode)

Trinkets:
Missing Poster (No Sacrifice Rooms)
Purple Heart (Greed Mode champions don't drop anything so this is detrimental)
Karma (Pretty sure Donation Machines never appear in Greed Mode)
Fragmented Card (No Secret Rooms)
A Lighter (Doesn't affect wave spawns)
Crystal Key (Same reason as Red Key)
Ice Cube (Doesn't affect wave spawns)
Nuh Uh! (No effect in Greed Mode)
Old Capacitor (Prevents your active item from charging but doesn't drop batteries during waves; purely detrimental)
Temporary Tattoo (No challenge rooms)

**Comment by Rchardon** [comment]
Missing poster still revives you as The Lost.
All other trinkets are already removed, see #164

**Comment by AyyItsClarkster** [comment]
Since when did Missing Poster do that? Evidently the wiki is outdated/incorrect, fair enough. You beat me to the trinkets, though it's worth adding the tag to the items to prevent Chaos from pulling them and so on.

Edit: The item description was worded a bit awkwardly so I misunderstood >.> that's my bad

**Comment by ZMBanshee** [comment]
Opening another issue for this was unnecessary, you could have just kept it contained in the first one. And yeah, there is a separate one for trinkets already.

**Comment by Rchardon** [comment]
@AyyItsClarkster Since Afterbirth according to the wiki : Dying in a Sacrifice Room while holding it unlocks The Lost. If The Lost is already unlocked, revives Isaac as The Lost if he dies anywhere, then disappears.
