### ISSUE TITLE
Some nolostbr and offensive tags issues

### ISSUE THREAD

**Issue by Neonomi** [UnderscoreKilburn/repentance-issues#265]
Should have nolostbr tag:
148 Infestation (proc on receiving damage)
393 Serpent Kiss (probably)
501 Greed's Gullet (health)
713 Sumptorium (it just kills you)
724 Hypercoagulation (health, proc on receiving damage)

Shouldn't have nolostbr tag:
326 Breath of Life (useful for curse room and devil beggars, Tooth and Nail does not have nolostbr tag as well)
300 Aries (speed up, can be used as damage)
549 Brittle Bones (+0.4 tears per second)
694 Heartbreak (if it's not intended)
413 Immaculate Conception (still works with soul hearts, even if you get The Relic this is nice for future babies)

Should have offensive tag:
83 The Nail (Book of Belial + Stompy)
178 Holy Water
549 Brittle Bones (+0.4 tears per second)
710 Bag of Crafting 

Shouldn't have offensive tag:
663 Tooth and Nail (imagine use it for dealing damage on Tainted Lost)

**Comment by ZMBanshee** [comment]
Aries just had the nolostbr tag removed in 1.7.7.
Holy Water has had the offensive tag since 1.7.5.
Bag of Crafting was purposefully excluded for the time being as the crafted items ignore T Lost's whitelist, but it could get the tag later.

Some of the others are oversights though, so thanks.
