### ISSUE TITLE
Activating Astral Projection in a room with rain effects crashes the game

### ISSUE THREAD

**Issue by kiwibird34** [UnderscoreKilburn/repentance-issues#297]
Similar issue to #47

https://user-images.githubusercontent.com/8262868/144728660-d3ddfc02-cc7e-481d-bb48-8dda1f6fde46.mp4

**Comment by ZMBanshee** [comment]
Easily reproducible, thanks.

**Comment by eyhung** [comment]
I don't know if this is similar, but when I activated Mr. Me in a boss room with rain effects today (Downpour or Dross II), and used it to pick up a Boss Item (playing Tainted Keeper so as to bypass the cost), the game also crashed.
