### ISSUE TITLE
Rag Man/Rag Mega's minions spawned through Delirious SOMETIMES softlock the game in boss rooms

### ISSUE THREAD

**Issue by YazawaAkio** [UnderscoreKilburn/repentance-issues#299]
Through (an excessive amount of) testings, friendly Rag Man's head and friendly Rag Mega's purple balls would sometimes be considered as enemies in the room, thus softlocking the game after the boss is defeated as they cannot be killed by you.

**Comment by ZMBanshee** [comment]
It seems to be caused by the flesh piles that the raglings create. If a ragling doesn't die, then the softlock doesn't occur.
