### ISSUE TITLE
Having the ability to control whether bum familiars can or cannot collect pickups

### ISSUE THREAD

**Issue by Greenness348** [UnderscoreKilburn/repentance-issues#307]
I think there should be a more controllable way to allow bums to gather pickups, it's frustrating right now to have them collect them against your will, so it could become detrimental to pick those items up depending on the floor because of that.

I suggest having the ability to toggle them with ctrl with both options being collect like it is now and not collect so it's on standby until you call it.

**Comment by ZMBanshee** [comment]
Goes against the spirit of the game honestly, it's like requesting Bob's Brain be changed to not damage you.

**Comment by Greenness348** [comment]
I guess they are both built on that same design mentality of being kind of trolly, so yeah fair enough I respect your opinion.
