### ISSUE TITLE
(Suggestion) Using the soul of a lost after loss of all hearts, after picking up an item from the devil

### ISSUE THREAD

**Issue by ghost** [UnderscoreKilburn/repentance-issues#311]
https://user-images.githubusercontent.com/95560899/144758159-beffbbe2-1da7-467c-98f3-d1afdaa3aa84.mp4

**Comment by ghost** [comment]
Of course, you need to respect the timing for the selection of the item. But I think this is a bug. 
Edit: Although it makes sense

**Comment by thereisnofuture1** [comment]
if you press card/pill right after picking up an item it works like animation cancel so that's why it was insta death probably.

**Comment by ghost** [comment]
> if you press card/pill right after picking up an item it works like animation cancel so that's why it was insta death probably.

Oh okay

**Comment by ZMBanshee** [comment]
This also makes zero sense to do. What are you going to do when the effect wears off? You'd leave the room and have no hearts left anyway.

**Comment by luni3359** [comment]
He was just experimenting, it's not like most players know the game inside and out.

**Comment by ghost** [comment]
Just suggested an idea, the type could be made a feature. Type no hearts, left the devil's room became a lost until the end of the game. It would be cool. But now it looks stupid.
