### ISSUE TITLE
Poison clouds created by Twisted Pair + Epic Fetus + Ipecac are damaging you

### ISSUE THREAD

**Issue by Rchardon** [UnderscoreKilburn/repentance-issues#32]

**Comment by ZMBanshee** [comment]
Tested this and it only happens with Ipecac, Bob's Curse is okay. Edited your title.

**Comment by Rchardon** [comment]
It also damage you with scorpio (maybe all items that poisons enemies ?)

**Comment by Neonomi** [comment]
Incubus included
