### ISSUE TITLE
Dropping and picking up the D Infinity messes up the current charge.

### ISSUE THREAD

**Issue by bathtubed** [UnderscoreKilburn/repentance-issues#325]
I believe this is true with any variable charge item but when you pick up a different active item and then re-pick up the d-infinity most often it wont be fully charged anymore and it will have a glitchy charge bar with 2 yellow ticks.
Even more, after a few rooms the item will be "charged" even when it shouldn't be and you can use it.
It's very inconsistent how it behaves but it will almost always mess up when you drop and pick it up in some way.

**Comment by itsrekhab** [comment]
This is the same for all items with variable charges, if there are more charges stored in the item than the default, the extra charges are stacked on top of each other (like with The Battery) and if they don't fit into 2x default charge capacity, they are trimmed out.
