### ISSUE TITLE
Damocles combined with Binge Eater causes infinite item duplication

### ISSUE THREAD

**Issue by toarch7** [UnderscoreKilburn/repentance-issues#33]
https://imgur.com/a/eEkCM9f

**Comment by toarch7** [comment]
Possibly curse of the blind is needed for replication

**Comment by ZMBanshee** [comment]
If you have any mods at all, I would try disabling them and restarting the game. I haven't been able to reproduce this. If you can find a way to consistently reproduce it, comment here again. Steps to reproduce would be helpful as well if possible.

**Comment by toarch7** [comment]
> If you have any mods at all, I would try disabling them and restarting the game. I haven't been able to reproduce this. If you can find a way to consistently reproduce it, comment here again. Steps to reproduce would be helpful as well if possible.

I had no mods enabled (and even installed) at that moment.


Also tried to reproduce the bug but the result was not the same.
I can mention some weird behavior that happened before: 
When I enter Dank Depths 1 devil deal, the damocles item seem not to switch between binge eater's hp up and the damocles itself. I took and used it in the devil room. After the boss item started to duplicate.

 I have record of this moment, but it seems to not have any worthwhile information.

**Comment by ZMBanshee** [comment]
We think we know what's causing these oddities now, so I'll close this, thanks.
