### ISSUE TITLE
Negative active item slots in AddCollectible access/overwrite memory

### ISSUE THREAD

**Issue by Buurazu** [UnderscoreKilburn/repentance-issues#348]
`Isaac.GetPlayer(0):AddCollectible(CollectibleType.COLLECTIBLE_RED_KEY, 0, false, -4)` will almost definitely crash the game, surely because it's writing arbitrary memory
-2 often crashes as well
using GetItemCharge or GetActiveItem with negative item slots returns random numbers, so it's accessing arbitrary memory

Item slots 4 and above can also cause unintended behavior and possibly unintended memory access

I found this by trying to make red door outlines appear without a Red Key item, and active item slot -1 does accomplish that without any issues that I can tell (aside from Red Key appearing in My Stuff). So if it's fixed, I'd just ask for a way to enable red door outlines safely in code :)

**Comment by epfly6** [comment]
Now, rewrite this in [modding issue tracker](https://github.com/Meowlala/RepentanceAPIIssueTracker)

**Comment by Buurazu** [comment]
oh, i see, ok
