### ISSUE TITLE
Getting Hit With Astral Projection in a Room With a Rain Effect Crashes the Game

### ISSUE THREAD

**Issue by AttackTeam1** [UnderscoreKilburn/repentance-issues#353]
Similar to _[this issue](https://github.com/UnderscoreKilburn/repentance-issues/issues/47)_, the game will crash if the player takes damage in a room with the same rain effect.

 _How To Reproduce:_ Enter Seed 43SV 6V6J. Enter Downpour 1 using the entrance on basement 1. Enter the secret room diagonally up to the starting room by bombing in from the wrath mini boss fight to the left of the starting room to obtain the item. Take Damage in the room directly above the boss room, and the game will crash.

**Comment by luni3359** [comment]
It's already been reported in issue #297
