### ISSUE TITLE
Greed tears turn invisible if he shoots on the same frame he's killed

### ISSUE THREAD

**Issue by Rchardon** [UnderscoreKilburn/repentance-issues#361]
Resulting in unavoidable damage
https://clips.twitch.tv/ThoughtfulVastMonitorTTours-My_kO2Rov0gOEBeg

**Comment by ZMBanshee** [comment]
Could be Technology Zero acting up here. It can still rarely damage you with certain synergies, Kil hasn't gotten around to fixing that yet as far as I know.

**Comment by Rchardon** [comment]
It seems it was indeed caused by multi baby + tech 0 since he lost the mantle on the frame Multi baby appeared with Quints. Closing this

**Comment by luni3359** [comment]
maybe it's worth pointing this to issue #1220, or some other issue that tracks all instances of tech zero dealing self-damage
