### ISSUE TITLE
Crash when Multidimensional Baby receives a lot of Mom's Knifes

### ISSUE THREAD

**Issue by Neonomi** [UnderscoreKilburn/repentance-issues#363]
Easy to reproduse with Mutant Spider + Twisted Pair + Incubus + Box of Friends

**Comment by ZMBanshee** [comment]
Was able to reproduce it, thanks. Took a bunch of Box of Friends duplicates (also gave myself Soy Milk just for the sake of trying this faster), and then it froze without properly crashing or creating a dmp.
