### ISSUE TITLE
Ultra Secret still can cause softlock

### ISSUE THREAD

**Issue by Neonomi** [UnderscoreKilburn/repentance-issues#367]
Steps to reproduce:

1. Hard mode as The Lost. Seed BHJE D92R
2. Enter item room
3. Go to second floor naturally
3. Get keys, money, bombs (i used skeleton key, boom!, a dollar)
4. Enter item room
5. Go to drownpoor naturally
6. Enter item room
7. Get Voodoo from the shop (Eternal D6 use)
8. Go to Mines naturally
9. Use k74 The Moon? card
10. You got softlocked

**Comment by AyyItsClarkster** [comment]
Interesting, in this example, the curse room appeared diagonally to both Curse Rooms, and it seems that Inverted Moon doesn't like opening a path back to the level if that would lead the player into a Curse Room; but in this case it had no other choice, so it just didn't open any rooms. Definitely something that needs a failsafe.

**Comment by luni3359** [comment]
You can also get softlocked if you get teleported to the ultra secret room in greed mode and it's adjacent to the treasure room.
