### ISSUE TITLE
Various rooms have door availability incorrectly set

### ISSUE THREAD

**Issue by kittenchilly** [UnderscoreKilburn/repentance-issues#37]
This can lead to softlocks, with the chance to have rooms generated with doors behind pits and rocks.

**Comment by ZMBanshee** [comment]
Dross 561 is known (inappropriate right side door enabled), are there any others? The bugged Dank Depths room on the console ports (the one with a pit blocking the top door) is already fixed in the PC version.

**Comment by kittenchilly** [comment]
I saw one Ashpit room that had doors behind pits. I don't know the exact name, but its a double wide room.

**Comment by ZMBanshee** [comment]
Alright, I've gone through all of them and they seem okay. Keep in mind that shortly after an update, people who are trying to continue a run started from the previous version of the game will likely experience corrupted rooms/floors. This will go away as soon as they start a new run and is a relatively temporary problem.
