### ISSUE TITLE
Dark Esau will charge at you during the transition phase when picking up dad's note

### ISSUE THREAD

**Issue by XwaeRr** [UnderscoreKilburn/repentance-issues#373]
![20211219193210_1](https://user-images.githubusercontent.com/79228762/146683158-ecfe92cb-db6d-4ec9-91e0-32a9f244bbb3.jpg)
esau will charge at you, when you're in the transition phase whenever you pick up dad's note, and it is just long enough for him to always get you while you're frozen
I understand that this issue is braindead easy to solve by just simply using anima sola before picking up the note , but this is the second run I lose due to me forgetting about it. If he cannot charge at you while you wait for mega satan to appear, why should he be able to charge there?

**Comment by ZMBanshee** [comment]
You're not frozen during this transition, you can move out of the way.

**Comment by XwaeRr** [comment]
yea, discovered that myself recently, quite amusing now xD
