### ISSUE TITLE
Dashing with Pony into the minecart in Mines II causes a softlock. 

### ISSUE THREAD

**Issue by freezingdart** [UnderscoreKilburn/repentance-issues#395]

**Comment by AyyItsClarkster** [comment]
It causes odd behavior (like Isaac maintaining flight in the first room after entering the mind shaft, but loses it in the next room) but I can't reproduce a soft lock.

**Comment by ZMBanshee** [comment]
I believe one of the patches has fixed this already without specifically mentioning it, so I'll close it now, but if you ever see this happen again then open a new issue about it.
