### ISSUE TITLE
Mom's Ring don't drop anything if no runes unlocked

### ISSUE THREAD

**Issue by Neonomi** [UnderscoreKilburn/repentance-issues#399]

**Comment by Neonomi** [comment]
After 1 rune unlock it starts drop rune shards

**Comment by Rchardon** [comment]
Same for Clear rune then ?

**Comment by Neonomi** [comment]
> Same for Clear rune then ?

you can't unlock clear rune without blank rune unlock

**Comment by Rchardon** [comment]
Oh i didn't knew about that, it's not even mentionned on platinumgod. Is it the only unlockable thing without a secret attached to it ?

**Comment by Neonomi** [comment]
Turns out, if there is no runes unlocked, rune shards doens't spawn at all.
