### ISSUE TITLE
Crash synergy

### ISSUE THREAD

**Issue by Eris-GitHub** [UnderscoreKilburn/repentance-issues#400]
C section + Spirit sword + Soy milk / Almond milk. Game crashes if you spawned some C section babies.

**Comment by AyyItsClarkster** [comment]
I can't reproduce this with either Soy or Almond Milk. Can you give steps to reproduce?

**Comment by Eris-GitHub** [comment]
I's sorry. I don't really know why can't it be reproduced now. It worked in 2 runs, once with Tech X and once with Dr. Fetus but I can't reproduce it even with this items so maybe this crashes was because of some different item used with this combination.
