### ISSUE TITLE
Sumptorium still can spawn with Lost's Birthright.

### ISSUE THREAD

**Issue by mouthwideopen** [UnderscoreKilburn/repentance-issues#405]
I saw an issue posted about this from 24 days ago, but it was tagged as "fixed in patch" so I'm assuming that meant the patch that came 2 days later, and from what I can tell via checking with the resource extractor, this wasn't remedied.

Anyways, Sumptorium still doesn't have the nolostbr tag. Lost obviously cant use it without dying, though, so it should.

**Comment by ZMBanshee** [comment]
The label is used when something is fixed internally but not publicly. If it's fixed in a publicly released update or is a duplicate it gets closed. It got fixed but just happened to not be included in the small update that went out days later.
