### ISSUE TITLE
1 Pip Dice Room only rerolls the player that activates it

### ISSUE THREAD

**Issue by kittenchilly** [UnderscoreKilburn/repentance-issues#417]
This seems like an oversight since I feel dice rooms are supposed to be floor-wide, so it should effect every player and all subplayers like j&e, t forgotten, etc.

**Comment by ZMBanshee** [comment]
It's not. The 6 pip one rerolls all players. This is an intentional difference.

**Comment by luni3359** [comment]
Why the arbitrary difference?
