### ISSUE TITLE
Bug with Soul of Isaac, and possibly Curse of the Blind

### ISSUE THREAD

**Issue by eyhung** [UnderscoreKilburn/repentance-issues#435]
I had a run where I used Clicker on Tainted Judas with Dead Cat active, to become Tainted Keeper with Dead Cat.  I went to the Void, there was Curse of the Blind on the level, died and respawned with 1 coin heart, found a Soul of Isaac, and said why not use it on a Monstro's Tooth that dropped in one of the boss rooms.  I timed it well and picked up Midnight Snack, but it didn't give me a coin heart!  Using the console to give me another midnight snack worked and I went back to 2 coin hearts, so something feels wrong.

**Comment by Rchardon** [comment]
Possibly related to #308 where the second item from the same pedestal doesn't grant the effects it should
