### ISSUE TITLE
Tainted Sub Horf and Tainted Faceless don't count for the Sin Collector achievement

### ISSUE THREAD

**Issue by Rchardon** [UnderscoreKilburn/repentance-issues#443]
![20220117232543_1](https://user-images.githubusercontent.com/33094562/149844602-e6b9f86b-1fe8-4361-98f3-0e0e6d10a726.jpg)
![20220117232532_1](https://user-images.githubusercontent.com/33094562/149844607-475a1aec-391c-471a-abf1-9564774eee66.jpg)

**Comment by ZMBanshee** [comment]
I know you made this first, but since this seems to be a general issue with the Bestiary and not specific to certain enemies I'm gonna leave the other issue open instead https://github.com/UnderscoreKilburn/repentance-issues/issues/448
