### ISSUE TITLE
Black Hole achievement is outdated

### ISSUE THREAD

**Issue by kittenchilly** [UnderscoreKilburn/repentance-issues#451]
In AB+, it was really easy to get the black hole achievement since Portals were everywhere. Now they are only in the Void and even then don't appear that often. I think they should get a new unlock condition, possibly something to do with Planetariums?

**Comment by ZMBanshee** [comment]
The ones in the Mausoleum count too. I was able to easily get it on my new saves.

**Comment by kittenchilly** [comment]
Oh really? Huh. Although it still doesn't seem like a completely intentional unlock method with how portals were reworked.
