### ISSUE TITLE
Crash while airborne and hit by airborne enemies, currently clueless on what the cause is

### ISSUE THREAD

**Issue by StOil-L** [UnderscoreKilburn/repentance-issues#454]
I've experienced a weird crash twice during a run as Keeper. However, I have no idea what specifically caused it. 
It happened once when I got hit by an airborne Trite while I was using my Wooden Nickel, then happened again when I got hit by a Spikeball without doing anything else. I might've been hit by airborne enemies before the Corpse floors but a crash didn't occur.
My guess is it's either related to Astral Projection or Trinity Shield not functioning correctly upon taking contact damage from temporarily airborne enemies, or even Keeper's health mechanic as a whole.
The seed is 2Z3C 6MQ8. Here are my items:
![image](https://user-images.githubusercontent.com/62429997/150656547-1a39bc9d-7932-4c0f-8cda-c8d2bf464b73.png)

I'm sorry I don't have much more details to share, I'm very puzzled about this.

**Comment by ZMBanshee** [comment]
Astral Projection does have a known crash issue. Maybe it happened in one of those bloody rooms in the Corpse?

https://github.com/UnderscoreKilburn/repentance-issues/issues/297

**Comment by StOil-L** [comment]
Now that you mention it, yes, I remember both instances of the crash happening in a bloody room. If there is indeed a crash issue regarding Astral Projection and reflections on a wet floor then this is likely the cause of the crash I've experienced.
