### ISSUE TITLE
If Blastocyst is killed while frozen, its frozen sprite will be changed to that of max size Blastocyst until unfrozen, no matter the size of the killed Blastocyst

### ISSUE THREAD

**Issue by MBCollector672** [UnderscoreKilburn/repentance-issues#456]
Title is mildly confusing, so I will clarify:

When I say Blastocyst sizes, I mean the whole, 1/2, and 1/4th sizes. The 1/8th Blastocyst does not have this issue.
This happens most frequently with Holy Water, and this is where I've observed the bug.

**Comment by ZMBanshee** [comment]
See https://github.com/UnderscoreKilburn/repentance-issues/issues/261
