### ISSUE TITLE
Triggering Specific Pill Effect Crashes the Game

### ISSUE THREAD

**Issue by AttackTeam1** [UnderscoreKilburn/repentance-issues#47]
A specific pill effect results in a crash.

_How to replicate_: enter the seed **Y86L 3WLM**

Go to Downpour I using the trapdoor on Cellar I, enter the library after obtaining a key from the L shaped room above the starting room, open the wooden chest, take the **_red pill_**. Tested with different characters, crashes regardless of choice.

Unable to identify the effect as the game crashes before the pill effect name displays.

**Comment by ZMBanshee** [comment]
Thanks for the specific steps, this was easily reproducible.

**Comment by UnderscoreKilburn** [comment]
Wow okay, the pill was I'm Excited and it seems to crash when in a room with rain in it. Good catch, should be fixed in the next patch, thanks!
