### ISSUE TITLE
Emperor doesn't teleport to Boss Room on Ashpit II

### ISSUE THREAD

**Issue by eyhung** [UnderscoreKilburn/repentance-issues#482]
seed with this issue: 1G8D TQB4 (Not sure if that B is an 8,. but I think it's a B). Was playing as TLost. Went to Ashpit II with an Emperor card, went south to the Boss Challenge Room, grabbed the item and used the card.  I didn't go to the Boss Room but to the room in front of it.

**Comment by ZMBanshee** [comment]
Looked at the seed and it has Curse of the Maze on that floor. It has always been capable of slightly messing with teleports.

**Comment by eyhung** [comment]
Ah, okay.
