### ISSUE TITLE
Magdalene + Birthright in Knife Piece 2 section

### ISSUE THREAD

**Issue by itsrekhab** [UnderscoreKilburn/repentance-issues#494]
Going to acquire Knife Piece 2 as Magdalene with Birthright will remove any health above the normal 12-heart limit and it won't be restored afterwards.

**Comment by ZMBanshee** [comment]
Also true for Keeper's birthright. https://github.com/UnderscoreKilburn/repentance-issues/issues/11 is also related. I may converge the items that inappropriately reset into one issue at some point.

**Comment by ZMBanshee** [comment]
Alright I did converge them recently into that other issue, so I'm closing this now, but thank you for the report.
