### ISSUE TITLE
Entering knife piece 2 area can sometimes crash the game

### ISSUE THREAD

**Issue by amb2127** [UnderscoreKilburn/repentance-issues#50]
https://user-images.githubusercontent.com/39502367/141404377-25e8315a-b066-44ce-adb3-bbed17a46095.mp4

**Comment by ZMBanshee** [comment]
Can you verify that this happens with 0 mods enabled? Go to your mods page and press TAB to toggle your mods off temporarily, restart the game (completely, not just the run), give yourself knife piece 1 (so the puzzle area generates), use the stage 4c command, then try this again.

Also, a list of all of your mods would be helpful.

**Comment by amb2127** [comment]
just an issue with some mods not having an updated items.xml
