### ISSUE TITLE
Tainted Jacob can prematurely end a Co-Op run by dying while being a co-op tiny ghost

### ISSUE THREAD

**Issue by ACakeWearingAHat** [UnderscoreKilburn/repentance-issues#500]
This bug does not occur with other characters, and can occur through a variety of ways. Dogma's static aura tears, the Greed button, Lava, and many other sources that can deal damage to co-op ghosts can kill Tainted Jacob when dead.

**Comment by Rchardon** [comment]
Fixed in beta

**Comment by Rchardon** [comment]
I think you can close this
