### ISSUE TITLE
Strawman's status resets upon leaving the Knife Piece mineshaft in Mines/Ashpit

### ISSUE THREAD

**Issue by YazawaAkio** [UnderscoreKilburn/repentance-issues#503]
During playtest and a based on a recent report, it's found that leaving the mineshaft will instead respawn an entirely new Strawman Keeper, thus resetting the items it control, even the resurrected transformation from items such as Judas' Shadow or Lazarus' Rags.

**Comment by ZMBanshee** [comment]
Merging all mineshaft item reset issues here https://github.com/UnderscoreKilburn/repentance-issues/issues/11
