### ISSUE TITLE
Hey, bug with brimstone, soy milk and epiphora

### ISSUE THREAD

**Issue by ghost** [UnderscoreKilburn/repentance-issues#522]
In general, when using brimstone with soy milk, if you increase the rate of fire, the damage will increase.
However, with Epiphora - the rate of fire increases, but the damage does not
Reddit video: https://www.reddit.com/r/bindingofisaac/comments/t30oqc/i_am_so_disappointed_this_isnt_a_synergy/?utm_medium=android_app&utm_source=share

**Comment by oddlibra** [comment]
idk how where you got the knowledge that tearrate somehow increases dmg on brimstone + soy milk, but it makes no sense and shouldn't work in practice. epiphora is working as intended (if you look closely, dmg is ticking much more often as tearrate increases)

**Comment by Neonomi** [comment]
In fact you getting buff only with fire rate above 15. in the video you had less than that. work as usual, althrough i would like to have buff with soy milk at any fire rate
