### ISSUE TITLE
Saturnus guarantees hits in some rooms

### ISSUE THREAD

**Issue by Danial29** [UnderscoreKilburn/repentance-issues#533]
Maybe, make Saturnus' tears ignore TNTs?

https://user-images.githubusercontent.com/95134927/157937847-c336df24-6c62-4e24-9228-99111e2029ec.mp4

**Comment by ProjectTZ** [comment]
As well as saturnus tears shouldn't be able to break obstacles at all (Terra/Acid + Saturnus in a place with mushrooms obstacles)
