### ISSUE TITLE
Black Rune Consumes Held Active Item

### ISSUE THREAD

**Issue by Connorsseur** [UnderscoreKilburn/repentance-issues#539]
When you are holding an active item, pick up a different active item, and then use a black rune, both items get completely deleted (the one already in your inventory *SHOULD* remain intact). Unsure if it's actually getting voided (and at least granting stats) or if it just outright deletes the held item with no perks.

**Comment by BadsyEdgecat** [comment]
by all logic this should be just functioning off the same logic where buying an item from a shop and then using void while you're holding it lets you void shop/devil deal items. i guess, like, just dont do that.
