### ISSUE TITLE
Suggestion (visual): Urn of souls + Judas' birthright

### ISSUE THREAD

**Issue by LegSow** [UnderscoreKilburn/repentance-issues#596]
When holding the open urn of souls with Judas, the glow inside the urn is blue even though it shoots red brimstone lasers. I don't know if it's possible to easily retexture for a single character but a cool touch like this would make the combo even cooler.

**Comment by ZMBanshee** [comment]
It glows red for me in both the HUD sprite and the player sprite, not sure if that's new or not but I'm gonna close this now.
