### ISSUE TITLE
Certain charge items prevent the player from shooting when reaching 30 tears or higher

### ISSUE THREAD

**Issue by ZMBanshee** [UnderscoreKilburn/repentance-issues#6]
These include Brimstone, Mom's Knife, and Monstro's Lung.

Chocolate Milk normally works at 30 TPS, but breaks when combined with Neptunus.

**Comment by ZMBanshee** [comment]
Now also includes C Section.

**Comment by Neonomi** [comment]
Just tested cursed eye breaks on 60 tps
