### ISSUE TITLE
Using Sumptorium during a room transition in alt path floors crashes the game

### ISSUE THREAD

**Issue by ACakeWearingAHat** [UnderscoreKilburn/repentance-issues#61]
Specifically a problem for Tainted Eve in the new update. Cycling clots with Sumptorium constantly is now a good idea, but if you are in the process of absorbing clots while you move to a new room, the game freezes and crashes.

**Comment by ACakeWearingAHat** [comment]
This appears to be specific to the alt path floors.

**Comment by ZMBanshee** [comment]
Duplicate of https://github.com/UnderscoreKilburn/repentance-issues/issues/54
