### ISSUE TITLE
Tainted Jacob issue

### ISSUE THREAD

**Issue by DunnaD** [UnderscoreKilburn/repentance-issues#624]
During a run, I encountered a ghost champion enemy. Because Dark Esau is still recognised by the game as an enemy, I am stuck in the room until the softlock timer ends.
On the most recent build btw

**Comment by DunnaD** [comment]
This is in Void, so I cannot bomb open the doors.

**Comment by ZMBanshee** [comment]
I'm like 99% sure this is caused by mods that replace the entities2.xml with an outdated copy.

**Comment by DunnaD** [comment]
> I'm like 99% sure this is caused by mods that replace the entities2.xml with an outdated copy.

alright, will look into mods that replace entities2.xml
