### ISSUE TITLE
Invalid doors in 00.special rooms

### ISSUE THREAD

**Issue by yfyfyfyfyfy** [UnderscoreKilburn/repentance-issues#671]
some rooms in `00.special rooms` have invalid doors.

![image](https://user-images.githubusercontent.com/100398180/165316676-ee3d88b4-5e49-40ea-b9e7-00a35fd3147f.png)

**Comment by yfyfyfyfyfy** [comment]
![image](https://user-images.githubusercontent.com/100398180/165318245-853ea9fc-1c00-4c57-a671-b1fd84a8ccc9.png)

and it looks like this room has only one single entrance?

**Comment by ZMBanshee** [comment]
Thanks for the list.
