### ISSUE TITLE
Normalized rooms

### ISSUE THREAD

**Issue by Lonrite** [UnderscoreKilburn/repentance-issues#692]
This one is actually a pretty huge issue imo, and way too little people bring it up especially post-Rep launch

This game has shit ton of content worth of rooms, but a lot of them only appear in Normal Mode 

A lot of normal mode rooms are harder than hard mode ones

So you basically arbitrarily lose out on like half the rooms the game has to offer just because, i think all rooms should be available in either modes - the other restrictions and rulesets grant hard mode its title anyway well enough already

**Comment by ZMBanshee** [comment]
Repentance did make it so normal mode rooms can generate in hard mode, just less likely.

**Comment by Lonrite** [comment]
that's neat actually, didn't know that
