### ISSUE TITLE
Character personalities & tight design traits to make gameplay more novel and interesting

### ISSUE THREAD

**Issue by Lonrite** [UnderscoreKilburn/repentance-issues#718]
Magdalene could have a passive, ongoing thirst for gluttony and eating Yum Heart opens up a hole in it to put an active item inside, however the hole grows up rather fast and you're forced to eat more to be able to use it and rip up the regenerated heart part
overeating would put maggie at a disadvantage if she indulges in her sin too much, there could be a bit more to it but i'm not sure if more would be necessary to avoid overdesigning

Lilith could have something similar with putting an active inside box of friends, but it'd only be possible for your friends to open it since Lilith is blind
friends that would only be able to do it if they're not scared (every time lilith gets hit they get scared and go farther from her, or closer if she no hits rooms for some time - similar to child leash)

and when they're in a child leash-ish state, when you do well, you're able to open it up

There's a looot more potential for stuff like this but this is what I had in mind for years even before Rep came out

**Comment by ZMBanshee** [comment]
Reworks for these characters aren't planned.

**Comment by Lonrite** [comment]
damn

**Comment by Lonrite** [comment]
I do think the chars could benefit from little things like that but I guess it's too late for that
funnily enough I'd even prefer Isaac without the D6 since i like the classic, non-gimmicky part of it a lot

wish there was at least 1 character without any gimmicks but i guess it's too late since D6 is iconic for him
