### ISSUE TITLE
T Maggie

### ISSUE THREAD

**Issue by Lonrite** [UnderscoreKilburn/repentance-issues#721]
this should be obvious enough but still mentioning just in case it didn't cross your mind before

if she ever makes it into dailies, her timely dying hearts shouldn't account for damage pen - this way you can play her the intended way without automatically losing but overextending and forgetting the mechanic still stays punishing

**Comment by ZMBanshee** [comment]
Yeah

**Comment by Lonrite** [comment]
noice
