### ISSUE TITLE
Hush, little baby, don't say a word

### ISSUE THREAD

**Issue by Lonrite** [UnderscoreKilburn/repentance-issues#722]
Hush's placement is anticlimactic and makes very little sense because you encounter a really powerful entity mid-late game, but not end game — a boss that's x100 more powerful than a boss you're gonna meet way later after him

at that point you would have less items compared to chest (meaning after hush you'll find at least 7-8 items on average with taking starting room chests into the account)

so if you kill arguably the hardest boss in the game at a point without those 7-8 items, why would you have any trouble with future stuff in the run? there's just no tension left anymore

there's 4 solutions to this:

1) make blue baby an actual boss fight where the guy starts up as someone who stands up, but with lower hp falls to the ground and slowly walks/crawls (opposite of isaac who's very interested reading Bible at first and stands up overtime) - this would be the afterthought of it where he realized how sinful and wrong everything is actually in his life 

2) make blue womb a short floor with a small amount of rooms, where each one of them is a state of grief with special enemies tied to 'em (which would be randomized each time since isaac's personality is everchanging) and hush being a short but chaotic boss fight that's less powerful than blue baby will be later on

3) make Hush the final boss of chest and put blue baby in blue womb, just keep the armor and maybe add 1 attack or two (the most controversial one and i'm not really sure how i feel about it)

4) just nerfing Hush (also fixing his buggy af state he has currently but that should be a universal fix not some option out of a few)

**Comment by Lonrite** [comment]
it really only makes sense from story's point of view since the guy shows up in his deathwish form when you break your mom's heart to the point she thinks about nothing but her son (which is why the heart changes to it lives with a baby being in it lol)

**Comment by Lonrite** [comment]
well i guess 30 minute mark makes sense also since i imagine that's how long it took isaac to suffocate in the chest

**Comment by ZMBanshee** [comment]
Maybe reopen this one and just say "Hush could use some bugfixes regarding his combo attacks" as per your 4th point.

**Comment by Lonrite** [comment]
> Maybe reopen this one and just say "Hush could use some bugfixes regarding his combo attacks" as per your 4th point.

reopen as in make a new issue or reopen this one and just edit everything out except the 4th pointer?

cause i did really mean everything I said here, but maybe it's too late for other pointer changes since Hush has been like that for years, if that's what you're implying
