### ISSUE TITLE
Epiphora + Monstro's Lung unable to fire correctly at low tear values [Bug]

### ISSUE THREAD

**Issue by SpoonPotato** [UnderscoreKilburn/repentance-issues#728]
With Epiphora + Monstro's Lung, Isaac is unable to fire if Epiphora is triggered while Monstro's Lung is charging up. Switching directions (thus cancelling the Epiphora boost) allows Isaac to shoot. This issue only occurs at low tear values (with Polyphemus for example) since it happens only when epiphora has time to activate before Monstro's Lung is finished charging.

**Comment by SpoonPotato** [comment]
idk how to add the actual bug label

**Comment by luni3359** [comment]
You can't, only @ZMBanshee can (and a few other people too)
