### ISSUE TITLE
Some keys not working

### ISSUE THREAD

**Issue by iamrepairmanman** [UnderscoreKilburn/repentance-issues#734]
I lost progress due to a steam cloud issue(maybe?). Either way, while I had a backup save from the beginning of the year, I lost significant progress.

I was unable to use alt+f2 to restore cheevos on the stat screen, and with mods enabled I wasn't able to access the debug console.

The debug console hasn't been working for months.

**Comment by ZMBanshee** [comment]
In Repentance simply having a mod enabled isn't enough to activate the debug console. You need to go to Documents -> My Games -> Binding of Isaac Repentance -> options.ini (open this with notepad) and find the following line:

EnableDebugConsole=0

Change the 0 to a 1 and save the file, then restart the game. Start a run and see if it works.

**Comment by iamrepairmanman** [comment]
I've had it enabled the whole time. I brought it up as an issue become it suddenly stopped working.

Just to be safe I even went into options.ini, double checked that it was really set to 1, and then was still unable to access it.

**Comment by iamrepairmanman** [comment]
apparently alt+f2 DOES work, but it doesn't grant completion marks despite apparently granting me the associated secrets

**Comment by iamrepairmanman** [comment]
Apparently because of windows 11, my saved game data was moved. Very cool
