### ISSUE TITLE
Enemy softlocked in the wall with suplex!

### ISSUE THREAD

**Issue by Rchardon** [UnderscoreKilburn/repentance-issues#737]
I don't know if this is specific to bumbino with his punch attack or if it can happen to other enemies

https://user-images.githubusercontent.com/33094562/173887920-9ef1174a-f97c-4097-b268-de8585e4d998.mp4

**Comment by ZMBanshee** [comment]
I think it's specific to Bumbino, I've seen others run into this before but it's really rare.
