### ISSUE TITLE
Necropolis #1092, psychic maw is in the wall

### ISSUE THREAD

**Issue by Rchardon** [UnderscoreKilburn/repentance-issues#771]
![Capture](https://user-images.githubusercontent.com/33094562/178009324-8f12a2ea-a8c2-43a2-bf90-f92e8836b9bf.PNG)

**Comment by ZMBanshee** [comment]
There are actually a bunch of Repentance rooms like this, but no worries, it was done on purpose. It's a way of spawning an enemy over a pit without having to leave ugly gaps where they spawned.
