### ISSUE TITLE
double pennies from humbling bundle don't work as expected with keeper

### ISSUE THREAD

**Issue by eyhung** [UnderscoreKilburn/repentance-issues#787]
When Keeper is generating double pennies with Humbling Bundle and has only 1 out of 3 coin hearts, touching a double penny only restores 1 coin heart rather than 2 as expected.

**Comment by eyhung** [comment]
(Might be because I have holy mantle, too.)

**Comment by ZMBanshee** [comment]
Duplicate of https://github.com/UnderscoreKilburn/repentance-issues/issues/275
