### ISSUE TITLE
if you have one of the key pieces and then you fight uriel and gabriel and kill them at the same time with a bomb or just debug 10 you will get an extra key piece

### ISSUE THREAD

**Issue by krispypants** [UnderscoreKilburn/repentance-issues#81]

**Comment by ZMBanshee** [comment]
You always get key pieces from angels as long as you aren't holding both key pieces yet. I don't think this is even a bug. You can use this to your advantage with items like Void or the D6.

**Comment by krispypants** [comment]
I mean you could say it's not a bug but it's definitely not intended.
