### ISSUE TITLE
Bumbino can make you drop coins while invincible

### ISSUE THREAD

**Issue by StOil-L** [UnderscoreKilburn/repentance-issues#818]
Playing Isaac lately, I've noticed a very odd behavior while fighting Bumbino. If you use Book of Shadows and hug him, you don't take damage but you still lose coins as if you were taking damage.

This doesn't happen with any other "greedy" enemy in the game, so I'm led to believe this isn't intended.

**Comment by Rchardon** [comment]
fixed in 1.9.7.8
