### ISSUE TITLE
Rune Shards do not spawn if no runes are unlocked, with runes turning into cards instead.

### ISSUE THREAD

**Issue by MrSeemsGood** [UnderscoreKilburn/repentance-issues#838]
Just... why? Isn't that exactly what Rune Shards were made for? What's the point of replacing runes with tarot cards if you can turn them into shards instead?

...I'd like to think this is an oversight that needs to be solved. Please don't tell me it's intentional, it's infuriating.

**Comment by Turtier** [comment]
This is untrue. Used debug to give myself rune bag on a fresh file, it dropped a shard. I also specifically remember seeing rune shards early in repentance on a new save file, and the challenges (and therefore all the rune unlocks) were something I did much later in that file.

**Comment by ZMBanshee** [comment]
It's intentional that they only start spawning when you unlock your first rune, I've asked Kil this question before.
