### ISSUE TITLE
Bucket of Lard & Lazarus

### ISSUE THREAD

**Issue by Lonrite** [UnderscoreKilburn/repentance-issues#844]
the thing seems to not work properly on him, i think when you're rezzed - when you pick it up it doesn't give you a single heart container. run-ruining especially if it's a daily

**Comment by ZMBanshee** [comment]
Dunno what you mean, works fine from what I tried. Post evidence?

**Comment by Lonrite** [comment]
> Dunno what you mean, works fine from what I tried. Post evidence?

it happened to me on yesterday's daily after i used soul of isaac on another item. maybe it's only bugged when you pick it up after that soulstone? 
i swear it didn't heal me up or give a single heart container, let alone two - like it just didn't do anything at all except granting -0.2 speed

might be really rare or inconsistent to reproduce but it exists lol - like that book of shadows bug i posted before

**Comment by ZMBanshee** [comment]
Oh, it's this then, bug with Soul of Isaac that doesn't give transformation progress/healing/pickups https://github.com/UnderscoreKilburn/repentance-issues/issues/435
