### ISSUE TITLE
Missing/outdated death portraits

### ISSUE THREAD

**Issue by ZMBanshee** [UnderscoreKilburn/repentance-issues#847]
Portraits are missing for:

-Spiked rocks (uses Isaac's face)
-Spiked chests (uses Isaac's face)
-Hell Game (uses Isaac's face)
-Confessional (uses Isaac's face)
-Mushroom farts (uses Isaac's face)
-Polyps (uses Isaac's face)

Portraits are outdated for:

-Rotgut phase 3 (uses the Antibirth design)

**Comment by im-tem** [comment]
you have missed mega fatty, he uses rebirth beta design for death portrait
