### ISSUE TITLE
Hearts spawned from items should have the player as their spawner entity (type, variant, subtype)

### ISSUE THREAD

**Issue by TiredFoks** [UnderscoreKilburn/repentance-issues#869]
Some Items like Squeezy or Crystal Ball spawn soul hearts that have player as their spawner entity, but some other items like Fortune Cookie or Soul Locket do not, which makes it kinda hard to determine what heart pickups were spawned by the player or they were spawned naturally by clearing a room.

**Comment by ZMBanshee** [comment]
Might be better to open an issue here instead https://github.com/Meowlala/RepentanceAPIIssueTracker/issues

**Comment by TiredFoks** [comment]
Ah, you're right, my bad haha
