### ISSUE TITLE
Keeper's Birthright is taken away during Key Piece 2 sequence, but not regranted

### ISSUE THREAD

**Issue by FloFluoro** [UnderscoreKilburn/repentance-issues#87]
If Keeper picks up Birthright before doing the Key Piece 2 sequence, it's revoked after entering the chase area, but never re-granted; Keeper will have the same amount of coin hearts he had prior to picking up Birthright.

**Comment by ncrecc** [comment]
May also apply to Maggy's Birthright if she has >12 hearts upon entering the mineshaft?

**Comment by aywee26** [comment]
Ran into the same issue.
Regular Keeper, didn't beat Hush yet.
Picked up Old Bandage, then bought Birthright. 4 HP.
Entered mine sequence with 4 HP, while wandering around lost 1 HP.
Regained it back by eating Puberty pills.
Seed: 8G46 NEMW
PC, no mods.

**Comment by ZMBanshee** [comment]
Duplicate of #11
