### ISSUE TITLE
Pin & The Frail

### ISSUE THREAD

**Issue by Lonrite** [UnderscoreKilburn/repentance-issues#876]
i know those bosses are laughably easy already but i wish they had at least a tiny tell for when they pop up, even if it's some sound instead of an animation.

it's the worst in caves boss challenge rooms where they can nearly insta jump at you. (sometimes frail can jump 2 times in a row wtih minimal distance from you and without a tell its impossible to dodge in time)

i know that if you stand in the middle usually you're safe from their very first pop-up but as i said, sometimes the secondary one can show up very fast after the first, and unlike the start of the fight - you can't predict it consistently at all so ultimately it doesn't feel like a deserved hit at all

even someone like Polycephalus / Stain / Cage, while having a bit of an unforgiving tell after first few secs at least give you a chance to fairly outplay them if you pay attention - so having those for Pin and Frail would be nice too

**Comment by ZMBanshee** [comment]
Edit this earlier post you opened instead because it looks almost the same to me https://github.com/UnderscoreKilburn/repentance-issues/issues/648

**Comment by Lonrite** [comment]
oh ye true
