### ISSUE TITLE
Crash combo probably with eye of greed

### ISSUE THREAD

**Issue by Neonomi** [UnderscoreKilburn/repentance-issues#88]
Crash happened twice, on Dinga and Blastocyst Medium enemies
Each time before crash you can hear Eye of Greed's proc sound
Source
https://youtu.be/zHo2gpSh2l8?t=9314
https://youtu.be/zHo2gpSh2l8?t=9541

Items in combo:
Tech X
Trisagion
Cricket's Body
Eutanasia
Eye of Greed
Mom's Contact
Angelic Prism
Bird's Eye
Continuum
Fate's Reward
A bunch of wisps

**Comment by UnderscoreKilburn** [comment]
Looks like Trisagion + Continuum was the culprit, thanks!
