### ISSUE TITLE
Moon? softlock

### ISSUE THREAD

**Issue by Lonrite** [UnderscoreKilburn/repentance-issues#897]
this issue is definitely known but bringing up and hoping its not a duplicate.

seed "ADMY JW0H" is a prime example of this in hard mode (occurs on 1st or 2nd floor), moon? sotftlocks you and you can't do anything at all

**Comment by ZMBanshee** [comment]
Duplicate of https://github.com/UnderscoreKilburn/repentance-issues/issues/367
