### ISSUE TITLE
Inconsistency in resurrection items on tainted chars

### ISSUE THREAD

**Issue by Rchardon** [UnderscoreKilburn/repentance-issues#901]
It feels weird that Ankh revives you into Tainted Blue Baby when you are T. Blue Baby but it revives you into normal Blue Baby when you are another tainted char. Same for Judas Shadow, Lazarus Rags and Missing Poster

**Comment by luni3359** [comment]
why are you closing these issues

**Comment by Rchardon** [comment]
Since Kilburn will soon stop working on the game, it's better if he focuses on real bugs
