### ISSUE TITLE
Dogma lyrics

### ISSUE THREAD

**Issue by Lonrite** [UnderscoreKilburn/repentance-issues#911]
As far as I know, Colossians 3:6 doesn't have a single translation where it says "The **angel** of God" is coming instead of anger/wrath of God.

yet this is what Dogma says instead of the original meaning

this could be intended for all I know considering how he transforms into angel phase 2 but could also be a mistake lost in translation so i'm pointing it out just in case, even though it's probably too late to change anything there

**Comment by Turtier** [comment]
I've always heard "anger". It can sometimes sound like the G is followed by an L sound, I can hear it if intentionally trying to hear for an L, but I hear "angle" not "angel", I'm pretty sure the slight L sound is just mishearing and the actual word is anger. The wiki page for living in the light also says anger (I don't think that's official just thought its worth noting)

**Comment by ZMBanshee** [comment]
It 100% says "anger" in the lyrics, you misheard it

**Comment by CoolG0101** [comment]
> It 100% says "anger" in the lyrics, you misheard it

don't know about that bro, I asked Ridiculon directly and that's what they had to say: https://www.dropbox.com/s/g494ncvql8z3z47/Ridiculon%20reply.PNG?dl=0

i don't mind either version much anyways since Dogma turns into an angel phase 2 anyways but yeah lol

**Comment by Lonrite** [comment]
> It 100% says "anger" in the lyrics, you misheard it

don't know about that bro, I asked Ridiculon directly and that's what they had to say: https://www.dropbox.com/s/g494ncvql8z3z47/Ridiculon%20reply.PNG?dl=0

i don't mind either version much anyways since Dogma turns into an angel phase 2 but yeah lol
