### ISSUE TITLE
Meatball ANM2 has a missing OverlayNullEffect Null Layer

### ISSUE THREAD

**Issue by epfly6** [UnderscoreKilburn/repentance-issues#913]
I don't know if it is worth mentioning such small technical nitpicks here, but Meatball doesn't have a specific layer for the status effects rendering. It also creates warning messages in the logs
![image](https://user-images.githubusercontent.com/36567300/188240660-68d7a8a1-c72a-41b0-8be1-8dce90bbd212.png)

**Comment by ZMBanshee** [comment]
Was worth mentioning yeah, especially since it causes a noticeable bug ingame (status effect icons not appearing for this enemy). Thanks.
