### ISSUE TITLE
Friendship Necklace / RC Remote

### ISSUE THREAD

**Issue by Lonrite** [UnderscoreKilburn/repentance-issues#914]
pretty sure I didn't post this yet so posting it to here that i wish those allowed (maybe chance-based) familiars to block bullets, or make them deal damage (for those that normally don't, slipped rib for example)

**Comment by ZMBanshee** [comment]
You actually did https://github.com/UnderscoreKilburn/repentance-issues/issues/653

**Comment by CoolG0101** [comment]
lol

**Comment by Lonrite** [comment]
lol, i had a feeling actually
