### ISSUE TITLE
Lodestone on Blue Baby

### ISSUE THREAD

**Issue by Lonrite** [UnderscoreKilburn/repentance-issues#930]
because of his fly orbitals, Lodestone makes Blue Baby unbeatable which makes the item untakeable sadly (even if normally it's pretty good), wish this was fixed
https://clips.twitch.tv/PuzzledLitigiousPigeonDBstyle-VVVFueZ5CvJtJxr-

**Comment by ZMBanshee** [comment]
Duplicate of https://github.com/UnderscoreKilburn/repentance-issues/issues/801
