### ISSUE TITLE
Esau Jr on Mega Satan dailies

### ISSUE THREAD

**Issue by Lonrite** [UnderscoreKilburn/repentance-issues#974]
if you use it and abandon the item, your key pieces will be taken away and you won't be able to enter mega satan fight. (unless you find the 2 key pieces later on in the run)

**Comment by CoolG0101** [comment]
nevermind, you get the key pieces back for the Mega Satan floor but the item hud and item penalty is kinda weird with it nonetheless i think

**Comment by Lonrite** [comment]
nevermind, you get the key pieces back for the Mega Satan floor but the item hud and item penalty is kinda weird with it nonetheless i think?
