### ISSUE TITLE
Can softlock game on Downpour 2 by creating a crawlspace while under white fire effect.

### ISSUE THREAD

**Issue by eyhung** [UnderscoreKilburn/repentance-issues#985]
I was on Downpour 2 and I had turned myself into a ghost with the white fire because I was Tainted Eden and wanted the Holy Mantle to preserve my items.  I found We Need to Go Deeper in a secret room and went out to find a tile where I could use it.  I saw such a tile, but didn't really notice that it was in a square inaccessible from the doorways.  I used the shovel, created a crawlspace, and went in.  I fought a haunt inside guarding an item, and when I went out, I was no longer a ghost and could no longer walk to the rest of the level, thus softlocking the game.

**Comment by eyhung** [comment]
To clarify I was not in the mirror world, which is why I reverted to non-ghost form.

**Comment by ZMBanshee** [comment]
Okay, so it sounds to me like you trapped yourself on an island you needed to be able to fly to access? This is probably the game's oldest softlock, and it can happen in a variety of ways, such as using The Bible, The Hanged Man, Pinking Shears, or any other similar temporary flight effect to access a crawlspace.

**Comment by ZMBanshee** [comment]
Actually I'm just going to close this since we have a related issue here about it https://github.com/UnderscoreKilburn/repentance-issues/issues/423
