### ISSUE TITLE
Items gained through full run rerolls do not make progress towards transformations

### ISSUE THREAD

**Issue by ZMBanshee** [UnderscoreKilburn/repentance-issues#99]
To clarify for other readers, yes you are supposed to be able to lose transformation progress when rerolling *out* of items. This bug is specifically about rerolling *into* items. They are supposed to count, and they do not, even if you have three at the same time.

**Comment by Rchardon** [comment]
Does the fix apply to T Eden too ?

**Comment by ZMBanshee** [comment]
Yes it does.
